// Code generated by ent, DO NOT EDIT.

package usagestat

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the usagestat type in the database.
	Label = "usage_stat"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBucketTime holds the string denoting the bucket_time field in the database.
	FieldBucketTime = "bucket_time"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldTemplateID holds the string denoting the template_id field in the database.
	FieldTemplateID = "template_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldIsError holds the string denoting the is_error field in the database.
	FieldIsError = "is_error"
	// FieldRequestCount holds the string denoting the request_count field in the database.
	FieldRequestCount = "request_count"
	// FieldErrorCount holds the string denoting the error_count field in the database.
	FieldErrorCount = "error_count"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldTotalTokens holds the string denoting the total_tokens field in the database.
	FieldTotalTokens = "total_tokens"
	// FieldCacheReadTokens holds the string denoting the cache_read_tokens field in the database.
	FieldCacheReadTokens = "cache_read_tokens"
	// FieldCacheCreationTokens holds the string denoting the cache_creation_tokens field in the database.
	FieldCacheCreationTokens = "cache_creation_tokens"
	// FieldCost holds the string denoting the cost field in the database.
	FieldCost = "cost"
	// FieldTotalLatencyMs holds the string denoting the total_latency_ms field in the database.
	FieldTotalLatencyMs = "total_latency_ms"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the usagestat in the database.
	Table = "usage_stats"
)

// Columns holds all SQL columns for usagestat fields.
var Columns = []string{
	FieldID,
	FieldBucketTime,
	FieldGroupID,
	FieldAccountID,
	FieldTemplateID,
	FieldUserID,
	FieldModel,
	FieldIsError,
	FieldRequestCount,
	FieldErrorCount,
	FieldInputTokens,
	FieldOutputTokens,
	FieldTotalTokens,
	FieldCacheReadTokens,
	FieldCacheCreationTokens,
	FieldCost,
	FieldTotalLatencyMs,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultGroupID holds the default value on creation for the "group_id" field.
	DefaultGroupID int64
	// DefaultAccountID holds the default value on creation for the "account_id" field.
	DefaultAccountID int64
	// DefaultTemplateID holds the default value on creation for the "template_id" field.
	DefaultTemplateID int64
	// DefaultUserID holds the default value on creation for the "user_id" field.
	DefaultUserID int64
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// DefaultIsError holds the default value on creation for the "is_error" field.
	DefaultIsError bool
	// DefaultRequestCount holds the default value on creation for the "request_count" field.
	DefaultRequestCount int64
	// DefaultErrorCount holds the default value on creation for the "error_count" field.
	DefaultErrorCount int64
	// DefaultInputTokens holds the default value on creation for the "input_tokens" field.
	DefaultInputTokens int64
	// DefaultOutputTokens holds the default value on creation for the "output_tokens" field.
	DefaultOutputTokens int64
	// DefaultTotalTokens holds the default value on creation for the "total_tokens" field.
	DefaultTotalTokens int64
	// DefaultCacheReadTokens holds the default value on creation for the "cache_read_tokens" field.
	DefaultCacheReadTokens int64
	// DefaultCacheCreationTokens holds the default value on creation for the "cache_creation_tokens" field.
	DefaultCacheCreationTokens int64
	// DefaultCost holds the default value on creation for the "cost" field.
	DefaultCost int64
	// DefaultTotalLatencyMs holds the default value on creation for the "total_latency_ms" field.
	DefaultTotalLatencyMs int64
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the UsageStat queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBucketTime orders the results by the bucket_time field.
func ByBucketTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBucketTime, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByTemplateID orders the results by the template_id field.
func ByTemplateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemplateID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByIsError orders the results by the is_error field.
func ByIsError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsError, opts...).ToFunc()
}

// ByRequestCount orders the results by the request_count field.
func ByRequestCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestCount, opts...).ToFunc()
}

// ByErrorCount orders the results by the error_count field.
func ByErrorCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCount, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByTotalTokens orders the results by the total_tokens field.
func ByTotalTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalTokens, opts...).ToFunc()
}

// ByCacheReadTokens orders the results by the cache_read_tokens field.
func ByCacheReadTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheReadTokens, opts...).ToFunc()
}

// ByCacheCreationTokens orders the results by the cache_creation_tokens field.
func ByCacheCreationTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheCreationTokens, opts...).ToFunc()
}

// ByCost orders the results by the cost field.
func ByCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCost, opts...).ToFunc()
}

// ByTotalLatencyMs orders the results by the total_latency_ms field.
func ByTotalLatencyMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalLatencyMs, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
