// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-proxy-mini/internal/ent/group"
	"go-proxy-mini/internal/ent/groupassignment"
	"go-proxy-mini/internal/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GroupAssignmentCreate is the builder for creating a GroupAssignment entity.
type GroupAssignmentCreate struct {
	config
	mutation *GroupAssignmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetGroupID sets the "group_id" field.
func (_c *GroupAssignmentCreate) SetGroupID(v int64) *GroupAssignmentCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *GroupAssignmentCreate) SetUserID(v int64) *GroupAssignmentCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPriceMultiplier sets the "price_multiplier" field.
func (_c *GroupAssignmentCreate) SetPriceMultiplier(v int) *GroupAssignmentCreate {
	_c.mutation.SetPriceMultiplier(v)
	return _c
}

// SetNillablePriceMultiplier sets the "price_multiplier" field if the given value is not nil.
func (_c *GroupAssignmentCreate) SetNillablePriceMultiplier(v *int) *GroupAssignmentCreate {
	if v != nil {
		_c.SetPriceMultiplier(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupAssignmentCreate) SetCreatedAt(v time.Time) *GroupAssignmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupAssignmentCreate) SetNillableCreatedAt(v *time.Time) *GroupAssignmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GroupAssignmentCreate) SetID(v int64) *GroupAssignmentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *GroupAssignmentCreate) SetGroup(v *Group) *GroupAssignmentCreate {
	return _c.SetGroupID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *GroupAssignmentCreate) SetUser(v *User) *GroupAssignmentCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the GroupAssignmentMutation object of the builder.
func (_c *GroupAssignmentCreate) Mutation() *GroupAssignmentMutation {
	return _c.mutation
}

// Save creates the GroupAssignment in the database.
func (_c *GroupAssignmentCreate) Save(ctx context.Context) (*GroupAssignment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupAssignmentCreate) SaveX(ctx context.Context) *GroupAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupAssignmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupAssignmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupAssignmentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := groupassignment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupAssignmentCreate) check() error {
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "GroupAssignment.group_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "GroupAssignment.user_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GroupAssignment.created_at"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "GroupAssignment.group"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "GroupAssignment.user"`)}
	}
	return nil
}

func (_c *GroupAssignmentCreate) sqlSave(ctx context.Context) (*GroupAssignment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupAssignmentCreate) createSpec() (*GroupAssignment, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupAssignment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(groupassignment.Table, sqlgraph.NewFieldSpec(groupassignment.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PriceMultiplier(); ok {
		_spec.SetField(groupassignment.FieldPriceMultiplier, field.TypeInt, value)
		_node.PriceMultiplier = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(groupassignment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupassignment.GroupTable,
			Columns: []string{groupassignment.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupassignment.UserTable,
			Columns: []string{groupassignment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupAssignment.Create().
//		SetGroupID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupAssignmentUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupAssignmentCreate) OnConflict(opts ...sql.ConflictOption) *GroupAssignmentUpsertOne {
	_c.conflict = opts
	return &GroupAssignmentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupAssignment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupAssignmentCreate) OnConflictColumns(columns ...string) *GroupAssignmentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupAssignmentUpsertOne{
		create: _c,
	}
}

type (
	// GroupAssignmentUpsertOne is the builder for "upsert"-ing
	//  one GroupAssignment node.
	GroupAssignmentUpsertOne struct {
		create *GroupAssignmentCreate
	}

	// GroupAssignmentUpsert is the "OnConflict" setter.
	GroupAssignmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetGroupID sets the "group_id" field.
func (u *GroupAssignmentUpsert) SetGroupID(v int64) *GroupAssignmentUpsert {
	u.Set(groupassignment.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupAssignmentUpsert) UpdateGroupID() *GroupAssignmentUpsert {
	u.SetExcluded(groupassignment.FieldGroupID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *GroupAssignmentUpsert) SetUserID(v int64) *GroupAssignmentUpsert {
	u.Set(groupassignment.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *GroupAssignmentUpsert) UpdateUserID() *GroupAssignmentUpsert {
	u.SetExcluded(groupassignment.FieldUserID)
	return u
}

// SetPriceMultiplier sets the "price_multiplier" field.
func (u *GroupAssignmentUpsert) SetPriceMultiplier(v int) *GroupAssignmentUpsert {
	u.Set(groupassignment.FieldPriceMultiplier, v)
	return u
}

// UpdatePriceMultiplier sets the "price_multiplier" field to the value that was provided on create.
func (u *GroupAssignmentUpsert) UpdatePriceMultiplier() *GroupAssignmentUpsert {
	u.SetExcluded(groupassignment.FieldPriceMultiplier)
	return u
}

// AddPriceMultiplier adds v to the "price_multiplier" field.
func (u *GroupAssignmentUpsert) AddPriceMultiplier(v int) *GroupAssignmentUpsert {
	u.Add(groupassignment.FieldPriceMultiplier, v)
	return u
}

// ClearPriceMultiplier clears the value of the "price_multiplier" field.
func (u *GroupAssignmentUpsert) ClearPriceMultiplier() *GroupAssignmentUpsert {
	u.SetNull(groupassignment.FieldPriceMultiplier)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *GroupAssignmentUpsert) SetCreatedAt(v time.Time) *GroupAssignmentUpsert {
	u.Set(groupassignment.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *GroupAssignmentUpsert) UpdateCreatedAt() *GroupAssignmentUpsert {
	u.SetExcluded(groupassignment.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.GroupAssignment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(groupassignment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GroupAssignmentUpsertOne) UpdateNewValues() *GroupAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(groupassignment.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupAssignment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GroupAssignmentUpsertOne) Ignore() *GroupAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupAssignmentUpsertOne) DoNothing() *GroupAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupAssignmentCreate.OnConflict
// documentation for more info.
func (u *GroupAssignmentUpsertOne) Update(set func(*GroupAssignmentUpsert)) *GroupAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupAssignmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GroupAssignmentUpsertOne) SetGroupID(v int64) *GroupAssignmentUpsertOne {
	return u.Update(func(s *GroupAssignmentUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupAssignmentUpsertOne) UpdateGroupID() *GroupAssignmentUpsertOne {
	return u.Update(func(s *GroupAssignmentUpsert) {
		s.UpdateGroupID()
	})
}

// SetUserID sets the "user_id" field.
func (u *GroupAssignmentUpsertOne) SetUserID(v int64) *GroupAssignmentUpsertOne {
	return u.Update(func(s *GroupAssignmentUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *GroupAssignmentUpsertOne) UpdateUserID() *GroupAssignmentUpsertOne {
	return u.Update(func(s *GroupAssignmentUpsert) {
		s.UpdateUserID()
	})
}

// SetPriceMultiplier sets the "price_multiplier" field.
func (u *GroupAssignmentUpsertOne) SetPriceMultiplier(v int) *GroupAssignmentUpsertOne {
	return u.Update(func(s *GroupAssignmentUpsert) {
		s.SetPriceMultiplier(v)
	})
}

// AddPriceMultiplier adds v to the "price_multiplier" field.
func (u *GroupAssignmentUpsertOne) AddPriceMultiplier(v int) *GroupAssignmentUpsertOne {
	return u.Update(func(s *GroupAssignmentUpsert) {
		s.AddPriceMultiplier(v)
	})
}

// UpdatePriceMultiplier sets the "price_multiplier" field to the value that was provided on create.
func (u *GroupAssignmentUpsertOne) UpdatePriceMultiplier() *GroupAssignmentUpsertOne {
	return u.Update(func(s *GroupAssignmentUpsert) {
		s.UpdatePriceMultiplier()
	})
}

// ClearPriceMultiplier clears the value of the "price_multiplier" field.
func (u *GroupAssignmentUpsertOne) ClearPriceMultiplier() *GroupAssignmentUpsertOne {
	return u.Update(func(s *GroupAssignmentUpsert) {
		s.ClearPriceMultiplier()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *GroupAssignmentUpsertOne) SetCreatedAt(v time.Time) *GroupAssignmentUpsertOne {
	return u.Update(func(s *GroupAssignmentUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *GroupAssignmentUpsertOne) UpdateCreatedAt() *GroupAssignmentUpsertOne {
	return u.Update(func(s *GroupAssignmentUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *GroupAssignmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupAssignmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupAssignmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GroupAssignmentUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GroupAssignmentUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GroupAssignmentCreateBulk is the builder for creating many GroupAssignment entities in bulk.
type GroupAssignmentCreateBulk struct {
	config
	err      error
	builders []*GroupAssignmentCreate
	conflict []sql.ConflictOption
}

// Save creates the GroupAssignment entities in the database.
func (_c *GroupAssignmentCreateBulk) Save(ctx context.Context) ([]*GroupAssignment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupAssignment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupAssignmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupAssignmentCreateBulk) SaveX(ctx context.Context) []*GroupAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupAssignmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupAssignmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupAssignment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupAssignmentUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupAssignmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *GroupAssignmentUpsertBulk {
	_c.conflict = opts
	return &GroupAssignmentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupAssignment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupAssignmentCreateBulk) OnConflictColumns(columns ...string) *GroupAssignmentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupAssignmentUpsertBulk{
		create: _c,
	}
}

// GroupAssignmentUpsertBulk is the builder for "upsert"-ing
// a bulk of GroupAssignment nodes.
type GroupAssignmentUpsertBulk struct {
	create *GroupAssignmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GroupAssignment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(groupassignment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GroupAssignmentUpsertBulk) UpdateNewValues() *GroupAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(groupassignment.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupAssignment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GroupAssignmentUpsertBulk) Ignore() *GroupAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupAssignmentUpsertBulk) DoNothing() *GroupAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupAssignmentCreateBulk.OnConflict
// documentation for more info.
func (u *GroupAssignmentUpsertBulk) Update(set func(*GroupAssignmentUpsert)) *GroupAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupAssignmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GroupAssignmentUpsertBulk) SetGroupID(v int64) *GroupAssignmentUpsertBulk {
	return u.Update(func(s *GroupAssignmentUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupAssignmentUpsertBulk) UpdateGroupID() *GroupAssignmentUpsertBulk {
	return u.Update(func(s *GroupAssignmentUpsert) {
		s.UpdateGroupID()
	})
}

// SetUserID sets the "user_id" field.
func (u *GroupAssignmentUpsertBulk) SetUserID(v int64) *GroupAssignmentUpsertBulk {
	return u.Update(func(s *GroupAssignmentUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *GroupAssignmentUpsertBulk) UpdateUserID() *GroupAssignmentUpsertBulk {
	return u.Update(func(s *GroupAssignmentUpsert) {
		s.UpdateUserID()
	})
}

// SetPriceMultiplier sets the "price_multiplier" field.
func (u *GroupAssignmentUpsertBulk) SetPriceMultiplier(v int) *GroupAssignmentUpsertBulk {
	return u.Update(func(s *GroupAssignmentUpsert) {
		s.SetPriceMultiplier(v)
	})
}

// AddPriceMultiplier adds v to the "price_multiplier" field.
func (u *GroupAssignmentUpsertBulk) AddPriceMultiplier(v int) *GroupAssignmentUpsertBulk {
	return u.Update(func(s *GroupAssignmentUpsert) {
		s.AddPriceMultiplier(v)
	})
}

// UpdatePriceMultiplier sets the "price_multiplier" field to the value that was provided on create.
func (u *GroupAssignmentUpsertBulk) UpdatePriceMultiplier() *GroupAssignmentUpsertBulk {
	return u.Update(func(s *GroupAssignmentUpsert) {
		s.UpdatePriceMultiplier()
	})
}

// ClearPriceMultiplier clears the value of the "price_multiplier" field.
func (u *GroupAssignmentUpsertBulk) ClearPriceMultiplier() *GroupAssignmentUpsertBulk {
	return u.Update(func(s *GroupAssignmentUpsert) {
		s.ClearPriceMultiplier()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *GroupAssignmentUpsertBulk) SetCreatedAt(v time.Time) *GroupAssignmentUpsertBulk {
	return u.Update(func(s *GroupAssignmentUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *GroupAssignmentUpsertBulk) UpdateCreatedAt() *GroupAssignmentUpsertBulk {
	return u.Update(func(s *GroupAssignmentUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *GroupAssignmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GroupAssignmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupAssignmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupAssignmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
