// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/is7qin/c3api/internal/ent/group"
	"github.com/is7qin/c3api/internal/ent/groupassignment"
	"github.com/is7qin/c3api/internal/ent/predicate"
	"github.com/is7qin/c3api/internal/ent/user"
)

// GroupAssignmentUpdate is the builder for updating GroupAssignment entities.
type GroupAssignmentUpdate struct {
	config
	hooks    []Hook
	mutation *GroupAssignmentMutation
}

// Where appends a list predicates to the GroupAssignmentUpdate builder.
func (_u *GroupAssignmentUpdate) Where(ps ...predicate.GroupAssignment) *GroupAssignmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GroupAssignmentUpdate) SetGroupID(v int64) *GroupAssignmentUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupAssignmentUpdate) SetNillableGroupID(v *int64) *GroupAssignmentUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *GroupAssignmentUpdate) SetUserID(v int64) *GroupAssignmentUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GroupAssignmentUpdate) SetNillableUserID(v *int64) *GroupAssignmentUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPriceMultiplier sets the "price_multiplier" field.
func (_u *GroupAssignmentUpdate) SetPriceMultiplier(v int) *GroupAssignmentUpdate {
	_u.mutation.ResetPriceMultiplier()
	_u.mutation.SetPriceMultiplier(v)
	return _u
}

// SetNillablePriceMultiplier sets the "price_multiplier" field if the given value is not nil.
func (_u *GroupAssignmentUpdate) SetNillablePriceMultiplier(v *int) *GroupAssignmentUpdate {
	if v != nil {
		_u.SetPriceMultiplier(*v)
	}
	return _u
}

// AddPriceMultiplier adds value to the "price_multiplier" field.
func (_u *GroupAssignmentUpdate) AddPriceMultiplier(v int) *GroupAssignmentUpdate {
	_u.mutation.AddPriceMultiplier(v)
	return _u
}

// ClearPriceMultiplier clears the value of the "price_multiplier" field.
func (_u *GroupAssignmentUpdate) ClearPriceMultiplier() *GroupAssignmentUpdate {
	_u.mutation.ClearPriceMultiplier()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GroupAssignmentUpdate) SetCreatedAt(v time.Time) *GroupAssignmentUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GroupAssignmentUpdate) SetNillableCreatedAt(v *time.Time) *GroupAssignmentUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *GroupAssignmentUpdate) SetGroup(v *Group) *GroupAssignmentUpdate {
	return _u.SetGroupID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *GroupAssignmentUpdate) SetUser(v *User) *GroupAssignmentUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the GroupAssignmentMutation object of the builder.
func (_u *GroupAssignmentUpdate) Mutation() *GroupAssignmentMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *GroupAssignmentUpdate) ClearGroup() *GroupAssignmentUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *GroupAssignmentUpdate) ClearUser() *GroupAssignmentUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupAssignmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupAssignmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupAssignmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupAssignmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupAssignmentUpdate) check() error {
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupAssignment.group"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupAssignment.user"`)
	}
	return nil
}

func (_u *GroupAssignmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupassignment.Table, groupassignment.Columns, sqlgraph.NewFieldSpec(groupassignment.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PriceMultiplier(); ok {
		_spec.SetField(groupassignment.FieldPriceMultiplier, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriceMultiplier(); ok {
		_spec.AddField(groupassignment.FieldPriceMultiplier, field.TypeInt, value)
	}
	if _u.mutation.PriceMultiplierCleared() {
		_spec.ClearField(groupassignment.FieldPriceMultiplier, field.TypeInt)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(groupassignment.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupassignment.GroupTable,
			Columns: []string{groupassignment.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupassignment.GroupTable,
			Columns: []string{groupassignment.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupassignment.UserTable,
			Columns: []string{groupassignment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupassignment.UserTable,
			Columns: []string{groupassignment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupassignment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupAssignmentUpdateOne is the builder for updating a single GroupAssignment entity.
type GroupAssignmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupAssignmentMutation
}

// SetGroupID sets the "group_id" field.
func (_u *GroupAssignmentUpdateOne) SetGroupID(v int64) *GroupAssignmentUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupAssignmentUpdateOne) SetNillableGroupID(v *int64) *GroupAssignmentUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *GroupAssignmentUpdateOne) SetUserID(v int64) *GroupAssignmentUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GroupAssignmentUpdateOne) SetNillableUserID(v *int64) *GroupAssignmentUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPriceMultiplier sets the "price_multiplier" field.
func (_u *GroupAssignmentUpdateOne) SetPriceMultiplier(v int) *GroupAssignmentUpdateOne {
	_u.mutation.ResetPriceMultiplier()
	_u.mutation.SetPriceMultiplier(v)
	return _u
}

// SetNillablePriceMultiplier sets the "price_multiplier" field if the given value is not nil.
func (_u *GroupAssignmentUpdateOne) SetNillablePriceMultiplier(v *int) *GroupAssignmentUpdateOne {
	if v != nil {
		_u.SetPriceMultiplier(*v)
	}
	return _u
}

// AddPriceMultiplier adds value to the "price_multiplier" field.
func (_u *GroupAssignmentUpdateOne) AddPriceMultiplier(v int) *GroupAssignmentUpdateOne {
	_u.mutation.AddPriceMultiplier(v)
	return _u
}

// ClearPriceMultiplier clears the value of the "price_multiplier" field.
func (_u *GroupAssignmentUpdateOne) ClearPriceMultiplier() *GroupAssignmentUpdateOne {
	_u.mutation.ClearPriceMultiplier()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GroupAssignmentUpdateOne) SetCreatedAt(v time.Time) *GroupAssignmentUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GroupAssignmentUpdateOne) SetNillableCreatedAt(v *time.Time) *GroupAssignmentUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *GroupAssignmentUpdateOne) SetGroup(v *Group) *GroupAssignmentUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *GroupAssignmentUpdateOne) SetUser(v *User) *GroupAssignmentUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the GroupAssignmentMutation object of the builder.
func (_u *GroupAssignmentUpdateOne) Mutation() *GroupAssignmentMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *GroupAssignmentUpdateOne) ClearGroup() *GroupAssignmentUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *GroupAssignmentUpdateOne) ClearUser() *GroupAssignmentUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the GroupAssignmentUpdate builder.
func (_u *GroupAssignmentUpdateOne) Where(ps ...predicate.GroupAssignment) *GroupAssignmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupAssignmentUpdateOne) Select(field string, fields ...string) *GroupAssignmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GroupAssignment entity.
func (_u *GroupAssignmentUpdateOne) Save(ctx context.Context) (*GroupAssignment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupAssignmentUpdateOne) SaveX(ctx context.Context) *GroupAssignment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupAssignmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupAssignmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupAssignmentUpdateOne) check() error {
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupAssignment.group"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupAssignment.user"`)
	}
	return nil
}

func (_u *GroupAssignmentUpdateOne) sqlSave(ctx context.Context) (_node *GroupAssignment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupassignment.Table, groupassignment.Columns, sqlgraph.NewFieldSpec(groupassignment.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GroupAssignment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, groupassignment.FieldID)
		for _, f := range fields {
			if !groupassignment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != groupassignment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PriceMultiplier(); ok {
		_spec.SetField(groupassignment.FieldPriceMultiplier, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriceMultiplier(); ok {
		_spec.AddField(groupassignment.FieldPriceMultiplier, field.TypeInt, value)
	}
	if _u.mutation.PriceMultiplierCleared() {
		_spec.ClearField(groupassignment.FieldPriceMultiplier, field.TypeInt)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(groupassignment.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupassignment.GroupTable,
			Columns: []string{groupassignment.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupassignment.GroupTable,
			Columns: []string{groupassignment.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupassignment.UserTable,
			Columns: []string{groupassignment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupassignment.UserTable,
			Columns: []string{groupassignment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &GroupAssignment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupassignment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
