// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/is7qin/c3api/internal/ent/group"
	"github.com/is7qin/c3api/internal/ent/groupupstream"
	"github.com/is7qin/c3api/internal/ent/upstream"
)

// GroupUpstream is the model entity for the GroupUpstream schema.
type GroupUpstream struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// UpstreamID holds the value of the "upstream_id" field.
	UpstreamID int64 `json:"upstream_id,omitempty"`
	// Weight holds the value of the "weight" field.
	Weight int `json:"weight,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority int `json:"priority,omitempty"`
	// MaxConcurrency holds the value of the "max_concurrency" field.
	MaxConcurrency int `json:"max_concurrency,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CooldownUntil holds the value of the "cooldown_until" field.
	CooldownUntil *time.Time `json:"cooldown_until,omitempty"`
	// FailureStreak holds the value of the "failure_streak" field.
	FailureStreak int `json:"failure_streak,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GroupUpstreamQuery when eager-loading is set.
	Edges        GroupUpstreamEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GroupUpstreamEdges holds the relations/edges for other nodes in the graph.
type GroupUpstreamEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// Upstream holds the value of the upstream edge.
	Upstream *Upstream `json:"upstream,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupUpstreamEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// UpstreamOrErr returns the Upstream value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupUpstreamEdges) UpstreamOrErr() (*Upstream, error) {
	if e.Upstream != nil {
		return e.Upstream, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: upstream.Label}
	}
	return nil, &NotLoadedError{edge: "upstream"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GroupUpstream) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case groupupstream.FieldEnabled:
			values[i] = new(sql.NullBool)
		case groupupstream.FieldID, groupupstream.FieldGroupID, groupupstream.FieldUpstreamID, groupupstream.FieldWeight, groupupstream.FieldPriority, groupupstream.FieldMaxConcurrency, groupupstream.FieldFailureStreak:
			values[i] = new(sql.NullInt64)
		case groupupstream.FieldLastError:
			values[i] = new(sql.NullString)
		case groupupstream.FieldCooldownUntil, groupupstream.FieldUpdatedAt, groupupstream.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GroupUpstream fields.
func (_m *GroupUpstream) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case groupupstream.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case groupupstream.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case groupupstream.FieldUpstreamID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_id", values[i])
			} else if value.Valid {
				_m.UpstreamID = value.Int64
			}
		case groupupstream.FieldWeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field weight", values[i])
			} else if value.Valid {
				_m.Weight = int(value.Int64)
			}
		case groupupstream.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case groupupstream.FieldMaxConcurrency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_concurrency", values[i])
			} else if value.Valid {
				_m.MaxConcurrency = int(value.Int64)
			}
		case groupupstream.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case groupupstream.FieldCooldownUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cooldown_until", values[i])
			} else if value.Valid {
				_m.CooldownUntil = new(time.Time)
				*_m.CooldownUntil = value.Time
			}
		case groupupstream.FieldFailureStreak:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field failure_streak", values[i])
			} else if value.Valid {
				_m.FailureStreak = int(value.Int64)
			}
		case groupupstream.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		case groupupstream.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case groupupstream.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GroupUpstream.
// This includes values selected through modifiers, order, etc.
func (_m *GroupUpstream) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the GroupUpstream entity.
func (_m *GroupUpstream) QueryGroup() *GroupQuery {
	return NewGroupUpstreamClient(_m.config).QueryGroup(_m)
}

// QueryUpstream queries the "upstream" edge of the GroupUpstream entity.
func (_m *GroupUpstream) QueryUpstream() *UpstreamQuery {
	return NewGroupUpstreamClient(_m.config).QueryUpstream(_m)
}

// Update returns a builder for updating this GroupUpstream.
// Note that you need to call GroupUpstream.Unwrap() before calling this method if this GroupUpstream
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GroupUpstream) Update() *GroupUpstreamUpdateOne {
	return NewGroupUpstreamClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GroupUpstream entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GroupUpstream) Unwrap() *GroupUpstream {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GroupUpstream is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GroupUpstream) String() string {
	var builder strings.Builder
	builder.WriteString("GroupUpstream(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("upstream_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpstreamID))
	builder.WriteString(", ")
	builder.WriteString("weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.Weight))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("max_concurrency=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxConcurrency))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	if v := _m.CooldownUntil; v != nil {
		builder.WriteString("cooldown_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("failure_streak=")
	builder.WriteString(fmt.Sprintf("%v", _m.FailureStreak))
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GroupUpstreams is a parsable slice of GroupUpstream.
type GroupUpstreams []*GroupUpstream
