// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/is7qin/c3api/internal/ent/imageprice"
)

// ImagePrice is the model entity for the ImagePrice schema.
type ImagePrice struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// InputImageTokenPricePerMillion holds the value of the "input_image_token_price_per_million" field.
	InputImageTokenPricePerMillion *int64 `json:"input_image_token_price_per_million,omitempty"`
	// OutputImageTokenPricePerMillion holds the value of the "output_image_token_price_per_million" field.
	OutputImageTokenPricePerMillion *int64 `json:"output_image_token_price_per_million,omitempty"`
	// OutputCostPerImageMilli holds the value of the "output_cost_per_image_milli" field.
	OutputCostPerImageMilli *int64 `json:"output_cost_per_image_milli,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider *string `json:"provider,omitempty"`
	// Raw holds the value of the "raw" field.
	Raw json.RawMessage `json:"raw,omitempty"`
	// Source holds the value of the "source" field.
	Source imageprice.Source `json:"source,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImagePrice) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case imageprice.FieldRaw:
			values[i] = new([]byte)
		case imageprice.FieldID, imageprice.FieldInputImageTokenPricePerMillion, imageprice.FieldOutputImageTokenPricePerMillion, imageprice.FieldOutputCostPerImageMilli:
			values[i] = new(sql.NullInt64)
		case imageprice.FieldModel, imageprice.FieldProvider, imageprice.FieldSource:
			values[i] = new(sql.NullString)
		case imageprice.FieldCreatedAt, imageprice.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImagePrice fields.
func (_m *ImagePrice) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case imageprice.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case imageprice.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case imageprice.FieldInputImageTokenPricePerMillion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_image_token_price_per_million", values[i])
			} else if value.Valid {
				_m.InputImageTokenPricePerMillion = new(int64)
				*_m.InputImageTokenPricePerMillion = value.Int64
			}
		case imageprice.FieldOutputImageTokenPricePerMillion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_image_token_price_per_million", values[i])
			} else if value.Valid {
				_m.OutputImageTokenPricePerMillion = new(int64)
				*_m.OutputImageTokenPricePerMillion = value.Int64
			}
		case imageprice.FieldOutputCostPerImageMilli:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_cost_per_image_milli", values[i])
			} else if value.Valid {
				_m.OutputCostPerImageMilli = new(int64)
				*_m.OutputCostPerImageMilli = value.Int64
			}
		case imageprice.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = new(string)
				*_m.Provider = value.String
			}
		case imageprice.FieldRaw:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field raw", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Raw); err != nil {
					return fmt.Errorf("unmarshal field raw: %w", err)
				}
			}
		case imageprice.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = imageprice.Source(value.String)
			}
		case imageprice.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case imageprice.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImagePrice.
// This includes values selected through modifiers, order, etc.
func (_m *ImagePrice) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ImagePrice.
// Note that you need to call ImagePrice.Unwrap() before calling this method if this ImagePrice
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ImagePrice) Update() *ImagePriceUpdateOne {
	return NewImagePriceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ImagePrice entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ImagePrice) Unwrap() *ImagePrice {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImagePrice is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ImagePrice) String() string {
	var builder strings.Builder
	builder.WriteString("ImagePrice(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	if v := _m.InputImageTokenPricePerMillion; v != nil {
		builder.WriteString("input_image_token_price_per_million=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OutputImageTokenPricePerMillion; v != nil {
		builder.WriteString("output_image_token_price_per_million=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OutputCostPerImageMilli; v != nil {
		builder.WriteString("output_cost_per_image_milli=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Provider; v != nil {
		builder.WriteString("provider=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("raw=")
	builder.WriteString(fmt.Sprintf("%v", _m.Raw))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(fmt.Sprintf("%v", _m.Source))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ImagePrices is a parsable slice of ImagePrice.
type ImagePrices []*ImagePrice
