// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/is7qin/c3api/internal/ent/referralreward"
)

// ReferralRewardCreate is the builder for creating a ReferralReward entity.
type ReferralRewardCreate struct {
	config
	mutation *ReferralRewardMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInviterID sets the "inviter_id" field.
func (_c *ReferralRewardCreate) SetInviterID(v int64) *ReferralRewardCreate {
	_c.mutation.SetInviterID(v)
	return _c
}

// SetInviteeID sets the "invitee_id" field.
func (_c *ReferralRewardCreate) SetInviteeID(v int64) *ReferralRewardCreate {
	_c.mutation.SetInviteeID(v)
	return _c
}

// SetSourceType sets the "source_type" field.
func (_c *ReferralRewardCreate) SetSourceType(v referralreward.SourceType) *ReferralRewardCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *ReferralRewardCreate) SetSourceID(v string) *ReferralRewardCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *ReferralRewardCreate) SetIdempotencyKey(v string) *ReferralRewardCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetBaseAmount sets the "base_amount" field.
func (_c *ReferralRewardCreate) SetBaseAmount(v int64) *ReferralRewardCreate {
	_c.mutation.SetBaseAmount(v)
	return _c
}

// SetRateBps sets the "rate_bps" field.
func (_c *ReferralRewardCreate) SetRateBps(v int) *ReferralRewardCreate {
	_c.mutation.SetRateBps(v)
	return _c
}

// SetNillableRateBps sets the "rate_bps" field if the given value is not nil.
func (_c *ReferralRewardCreate) SetNillableRateBps(v *int) *ReferralRewardCreate {
	if v != nil {
		_c.SetRateBps(*v)
	}
	return _c
}

// SetRewardAmount sets the "reward_amount" field.
func (_c *ReferralRewardCreate) SetRewardAmount(v int64) *ReferralRewardCreate {
	_c.mutation.SetRewardAmount(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ReferralRewardCreate) SetStatus(v referralreward.Status) *ReferralRewardCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ReferralRewardCreate) SetNillableStatus(v *referralreward.Status) *ReferralRewardCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAvailableAt sets the "available_at" field.
func (_c *ReferralRewardCreate) SetAvailableAt(v time.Time) *ReferralRewardCreate {
	_c.mutation.SetAvailableAt(v)
	return _c
}

// SetCreditedAt sets the "credited_at" field.
func (_c *ReferralRewardCreate) SetCreditedAt(v time.Time) *ReferralRewardCreate {
	_c.mutation.SetCreditedAt(v)
	return _c
}

// SetNillableCreditedAt sets the "credited_at" field if the given value is not nil.
func (_c *ReferralRewardCreate) SetNillableCreditedAt(v *time.Time) *ReferralRewardCreate {
	if v != nil {
		_c.SetCreditedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReferralRewardCreate) SetCreatedAt(v time.Time) *ReferralRewardCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReferralRewardCreate) SetNillableCreatedAt(v *time.Time) *ReferralRewardCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ReferralRewardCreate) SetID(v int64) *ReferralRewardCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ReferralRewardMutation object of the builder.
func (_c *ReferralRewardCreate) Mutation() *ReferralRewardMutation {
	return _c.mutation
}

// Save creates the ReferralReward in the database.
func (_c *ReferralRewardCreate) Save(ctx context.Context) (*ReferralReward, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReferralRewardCreate) SaveX(ctx context.Context) *ReferralReward {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralRewardCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralRewardCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReferralRewardCreate) defaults() {
	if _, ok := _c.mutation.RateBps(); !ok {
		v := referralreward.DefaultRateBps
		_c.mutation.SetRateBps(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := referralreward.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := referralreward.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReferralRewardCreate) check() error {
	if _, ok := _c.mutation.InviterID(); !ok {
		return &ValidationError{Name: "inviter_id", err: errors.New(`ent: missing required field "ReferralReward.inviter_id"`)}
	}
	if _, ok := _c.mutation.InviteeID(); !ok {
		return &ValidationError{Name: "invitee_id", err: errors.New(`ent: missing required field "ReferralReward.invitee_id"`)}
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New(`ent: missing required field "ReferralReward.source_type"`)}
	}
	if v, ok := _c.mutation.SourceType(); ok {
		if err := referralreward.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "ReferralReward.source_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`ent: missing required field "ReferralReward.source_id"`)}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "ReferralReward.idempotency_key"`)}
	}
	if _, ok := _c.mutation.BaseAmount(); !ok {
		return &ValidationError{Name: "base_amount", err: errors.New(`ent: missing required field "ReferralReward.base_amount"`)}
	}
	if _, ok := _c.mutation.RateBps(); !ok {
		return &ValidationError{Name: "rate_bps", err: errors.New(`ent: missing required field "ReferralReward.rate_bps"`)}
	}
	if _, ok := _c.mutation.RewardAmount(); !ok {
		return &ValidationError{Name: "reward_amount", err: errors.New(`ent: missing required field "ReferralReward.reward_amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ReferralReward.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := referralreward.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReferralReward.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AvailableAt(); !ok {
		return &ValidationError{Name: "available_at", err: errors.New(`ent: missing required field "ReferralReward.available_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ReferralReward.created_at"`)}
	}
	return nil
}

func (_c *ReferralRewardCreate) sqlSave(ctx context.Context) (*ReferralReward, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReferralRewardCreate) createSpec() (*ReferralReward, *sqlgraph.CreateSpec) {
	var (
		_node = &ReferralReward{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(referralreward.Table, sqlgraph.NewFieldSpec(referralreward.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.InviterID(); ok {
		_spec.SetField(referralreward.FieldInviterID, field.TypeInt64, value)
		_node.InviterID = value
	}
	if value, ok := _c.mutation.InviteeID(); ok {
		_spec.SetField(referralreward.FieldInviteeID, field.TypeInt64, value)
		_node.InviteeID = value
	}
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(referralreward.FieldSourceType, field.TypeEnum, value)
		_node.SourceType = value
	}
	if value, ok := _c.mutation.SourceID(); ok {
		_spec.SetField(referralreward.FieldSourceID, field.TypeString, value)
		_node.SourceID = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(referralreward.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.BaseAmount(); ok {
		_spec.SetField(referralreward.FieldBaseAmount, field.TypeInt64, value)
		_node.BaseAmount = value
	}
	if value, ok := _c.mutation.RateBps(); ok {
		_spec.SetField(referralreward.FieldRateBps, field.TypeInt, value)
		_node.RateBps = value
	}
	if value, ok := _c.mutation.RewardAmount(); ok {
		_spec.SetField(referralreward.FieldRewardAmount, field.TypeInt64, value)
		_node.RewardAmount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(referralreward.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AvailableAt(); ok {
		_spec.SetField(referralreward.FieldAvailableAt, field.TypeTime, value)
		_node.AvailableAt = value
	}
	if value, ok := _c.mutation.CreditedAt(); ok {
		_spec.SetField(referralreward.FieldCreditedAt, field.TypeTime, value)
		_node.CreditedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(referralreward.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReferralReward.Create().
//		SetInviterID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralRewardUpsert) {
//			SetInviterID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralRewardCreate) OnConflict(opts ...sql.ConflictOption) *ReferralRewardUpsertOne {
	_c.conflict = opts
	return &ReferralRewardUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReferralReward.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralRewardCreate) OnConflictColumns(columns ...string) *ReferralRewardUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralRewardUpsertOne{
		create: _c,
	}
}

type (
	// ReferralRewardUpsertOne is the builder for "upsert"-ing
	//  one ReferralReward node.
	ReferralRewardUpsertOne struct {
		create *ReferralRewardCreate
	}

	// ReferralRewardUpsert is the "OnConflict" setter.
	ReferralRewardUpsert struct {
		*sql.UpdateSet
	}
)

// SetInviterID sets the "inviter_id" field.
func (u *ReferralRewardUpsert) SetInviterID(v int64) *ReferralRewardUpsert {
	u.Set(referralreward.FieldInviterID, v)
	return u
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateInviterID() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldInviterID)
	return u
}

// AddInviterID adds v to the "inviter_id" field.
func (u *ReferralRewardUpsert) AddInviterID(v int64) *ReferralRewardUpsert {
	u.Add(referralreward.FieldInviterID, v)
	return u
}

// SetInviteeID sets the "invitee_id" field.
func (u *ReferralRewardUpsert) SetInviteeID(v int64) *ReferralRewardUpsert {
	u.Set(referralreward.FieldInviteeID, v)
	return u
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateInviteeID() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldInviteeID)
	return u
}

// AddInviteeID adds v to the "invitee_id" field.
func (u *ReferralRewardUpsert) AddInviteeID(v int64) *ReferralRewardUpsert {
	u.Add(referralreward.FieldInviteeID, v)
	return u
}

// SetSourceType sets the "source_type" field.
func (u *ReferralRewardUpsert) SetSourceType(v referralreward.SourceType) *ReferralRewardUpsert {
	u.Set(referralreward.FieldSourceType, v)
	return u
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateSourceType() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldSourceType)
	return u
}

// SetSourceID sets the "source_id" field.
func (u *ReferralRewardUpsert) SetSourceID(v string) *ReferralRewardUpsert {
	u.Set(referralreward.FieldSourceID, v)
	return u
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateSourceID() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldSourceID)
	return u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *ReferralRewardUpsert) SetIdempotencyKey(v string) *ReferralRewardUpsert {
	u.Set(referralreward.FieldIdempotencyKey, v)
	return u
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateIdempotencyKey() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldIdempotencyKey)
	return u
}

// SetBaseAmount sets the "base_amount" field.
func (u *ReferralRewardUpsert) SetBaseAmount(v int64) *ReferralRewardUpsert {
	u.Set(referralreward.FieldBaseAmount, v)
	return u
}

// UpdateBaseAmount sets the "base_amount" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateBaseAmount() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldBaseAmount)
	return u
}

// AddBaseAmount adds v to the "base_amount" field.
func (u *ReferralRewardUpsert) AddBaseAmount(v int64) *ReferralRewardUpsert {
	u.Add(referralreward.FieldBaseAmount, v)
	return u
}

// SetRateBps sets the "rate_bps" field.
func (u *ReferralRewardUpsert) SetRateBps(v int) *ReferralRewardUpsert {
	u.Set(referralreward.FieldRateBps, v)
	return u
}

// UpdateRateBps sets the "rate_bps" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateRateBps() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldRateBps)
	return u
}

// AddRateBps adds v to the "rate_bps" field.
func (u *ReferralRewardUpsert) AddRateBps(v int) *ReferralRewardUpsert {
	u.Add(referralreward.FieldRateBps, v)
	return u
}

// SetRewardAmount sets the "reward_amount" field.
func (u *ReferralRewardUpsert) SetRewardAmount(v int64) *ReferralRewardUpsert {
	u.Set(referralreward.FieldRewardAmount, v)
	return u
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateRewardAmount() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldRewardAmount)
	return u
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *ReferralRewardUpsert) AddRewardAmount(v int64) *ReferralRewardUpsert {
	u.Add(referralreward.FieldRewardAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *ReferralRewardUpsert) SetStatus(v referralreward.Status) *ReferralRewardUpsert {
	u.Set(referralreward.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateStatus() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldStatus)
	return u
}

// SetAvailableAt sets the "available_at" field.
func (u *ReferralRewardUpsert) SetAvailableAt(v time.Time) *ReferralRewardUpsert {
	u.Set(referralreward.FieldAvailableAt, v)
	return u
}

// UpdateAvailableAt sets the "available_at" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateAvailableAt() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldAvailableAt)
	return u
}

// SetCreditedAt sets the "credited_at" field.
func (u *ReferralRewardUpsert) SetCreditedAt(v time.Time) *ReferralRewardUpsert {
	u.Set(referralreward.FieldCreditedAt, v)
	return u
}

// UpdateCreditedAt sets the "credited_at" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateCreditedAt() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldCreditedAt)
	return u
}

// ClearCreditedAt clears the value of the "credited_at" field.
func (u *ReferralRewardUpsert) ClearCreditedAt() *ReferralRewardUpsert {
	u.SetNull(referralreward.FieldCreditedAt)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *ReferralRewardUpsert) SetCreatedAt(v time.Time) *ReferralRewardUpsert {
	u.Set(referralreward.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateCreatedAt() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ReferralReward.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(referralreward.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ReferralRewardUpsertOne) UpdateNewValues() *ReferralRewardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(referralreward.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReferralReward.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ReferralRewardUpsertOne) Ignore() *ReferralRewardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralRewardUpsertOne) DoNothing() *ReferralRewardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralRewardCreate.OnConflict
// documentation for more info.
func (u *ReferralRewardUpsertOne) Update(set func(*ReferralRewardUpsert)) *ReferralRewardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralRewardUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviterID sets the "inviter_id" field.
func (u *ReferralRewardUpsertOne) SetInviterID(v int64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetInviterID(v)
	})
}

// AddInviterID adds v to the "inviter_id" field.
func (u *ReferralRewardUpsertOne) AddInviterID(v int64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddInviterID(v)
	})
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateInviterID() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateInviterID()
	})
}

// SetInviteeID sets the "invitee_id" field.
func (u *ReferralRewardUpsertOne) SetInviteeID(v int64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetInviteeID(v)
	})
}

// AddInviteeID adds v to the "invitee_id" field.
func (u *ReferralRewardUpsertOne) AddInviteeID(v int64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddInviteeID(v)
	})
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateInviteeID() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateInviteeID()
	})
}

// SetSourceType sets the "source_type" field.
func (u *ReferralRewardUpsertOne) SetSourceType(v referralreward.SourceType) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateSourceType() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateSourceType()
	})
}

// SetSourceID sets the "source_id" field.
func (u *ReferralRewardUpsertOne) SetSourceID(v string) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateSourceID() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateSourceID()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *ReferralRewardUpsertOne) SetIdempotencyKey(v string) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateIdempotencyKey() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// SetBaseAmount sets the "base_amount" field.
func (u *ReferralRewardUpsertOne) SetBaseAmount(v int64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetBaseAmount(v)
	})
}

// AddBaseAmount adds v to the "base_amount" field.
func (u *ReferralRewardUpsertOne) AddBaseAmount(v int64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddBaseAmount(v)
	})
}

// UpdateBaseAmount sets the "base_amount" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateBaseAmount() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateBaseAmount()
	})
}

// SetRateBps sets the "rate_bps" field.
func (u *ReferralRewardUpsertOne) SetRateBps(v int) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetRateBps(v)
	})
}

// AddRateBps adds v to the "rate_bps" field.
func (u *ReferralRewardUpsertOne) AddRateBps(v int) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddRateBps(v)
	})
}

// UpdateRateBps sets the "rate_bps" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateRateBps() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateRateBps()
	})
}

// SetRewardAmount sets the "reward_amount" field.
func (u *ReferralRewardUpsertOne) SetRewardAmount(v int64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetRewardAmount(v)
	})
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *ReferralRewardUpsertOne) AddRewardAmount(v int64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddRewardAmount(v)
	})
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateRewardAmount() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateRewardAmount()
	})
}

// SetStatus sets the "status" field.
func (u *ReferralRewardUpsertOne) SetStatus(v referralreward.Status) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateStatus() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateStatus()
	})
}

// SetAvailableAt sets the "available_at" field.
func (u *ReferralRewardUpsertOne) SetAvailableAt(v time.Time) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetAvailableAt(v)
	})
}

// UpdateAvailableAt sets the "available_at" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateAvailableAt() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateAvailableAt()
	})
}

// SetCreditedAt sets the "credited_at" field.
func (u *ReferralRewardUpsertOne) SetCreditedAt(v time.Time) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetCreditedAt(v)
	})
}

// UpdateCreditedAt sets the "credited_at" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateCreditedAt() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateCreditedAt()
	})
}

// ClearCreditedAt clears the value of the "credited_at" field.
func (u *ReferralRewardUpsertOne) ClearCreditedAt() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.ClearCreditedAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ReferralRewardUpsertOne) SetCreatedAt(v time.Time) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateCreatedAt() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *ReferralRewardUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralRewardCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralRewardUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ReferralRewardUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ReferralRewardUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ReferralRewardCreateBulk is the builder for creating many ReferralReward entities in bulk.
type ReferralRewardCreateBulk struct {
	config
	err      error
	builders []*ReferralRewardCreate
	conflict []sql.ConflictOption
}

// Save creates the ReferralReward entities in the database.
func (_c *ReferralRewardCreateBulk) Save(ctx context.Context) ([]*ReferralReward, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReferralReward, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReferralRewardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReferralRewardCreateBulk) SaveX(ctx context.Context) []*ReferralReward {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralRewardCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralRewardCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReferralReward.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralRewardUpsert) {
//			SetInviterID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralRewardCreateBulk) OnConflict(opts ...sql.ConflictOption) *ReferralRewardUpsertBulk {
	_c.conflict = opts
	return &ReferralRewardUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReferralReward.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralRewardCreateBulk) OnConflictColumns(columns ...string) *ReferralRewardUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralRewardUpsertBulk{
		create: _c,
	}
}

// ReferralRewardUpsertBulk is the builder for "upsert"-ing
// a bulk of ReferralReward nodes.
type ReferralRewardUpsertBulk struct {
	create *ReferralRewardCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ReferralReward.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(referralreward.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ReferralRewardUpsertBulk) UpdateNewValues() *ReferralRewardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(referralreward.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReferralReward.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ReferralRewardUpsertBulk) Ignore() *ReferralRewardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralRewardUpsertBulk) DoNothing() *ReferralRewardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralRewardCreateBulk.OnConflict
// documentation for more info.
func (u *ReferralRewardUpsertBulk) Update(set func(*ReferralRewardUpsert)) *ReferralRewardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralRewardUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviterID sets the "inviter_id" field.
func (u *ReferralRewardUpsertBulk) SetInviterID(v int64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetInviterID(v)
	})
}

// AddInviterID adds v to the "inviter_id" field.
func (u *ReferralRewardUpsertBulk) AddInviterID(v int64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddInviterID(v)
	})
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateInviterID() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateInviterID()
	})
}

// SetInviteeID sets the "invitee_id" field.
func (u *ReferralRewardUpsertBulk) SetInviteeID(v int64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetInviteeID(v)
	})
}

// AddInviteeID adds v to the "invitee_id" field.
func (u *ReferralRewardUpsertBulk) AddInviteeID(v int64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddInviteeID(v)
	})
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateInviteeID() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateInviteeID()
	})
}

// SetSourceType sets the "source_type" field.
func (u *ReferralRewardUpsertBulk) SetSourceType(v referralreward.SourceType) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateSourceType() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateSourceType()
	})
}

// SetSourceID sets the "source_id" field.
func (u *ReferralRewardUpsertBulk) SetSourceID(v string) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateSourceID() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateSourceID()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *ReferralRewardUpsertBulk) SetIdempotencyKey(v string) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateIdempotencyKey() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// SetBaseAmount sets the "base_amount" field.
func (u *ReferralRewardUpsertBulk) SetBaseAmount(v int64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetBaseAmount(v)
	})
}

// AddBaseAmount adds v to the "base_amount" field.
func (u *ReferralRewardUpsertBulk) AddBaseAmount(v int64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddBaseAmount(v)
	})
}

// UpdateBaseAmount sets the "base_amount" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateBaseAmount() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateBaseAmount()
	})
}

// SetRateBps sets the "rate_bps" field.
func (u *ReferralRewardUpsertBulk) SetRateBps(v int) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetRateBps(v)
	})
}

// AddRateBps adds v to the "rate_bps" field.
func (u *ReferralRewardUpsertBulk) AddRateBps(v int) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddRateBps(v)
	})
}

// UpdateRateBps sets the "rate_bps" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateRateBps() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateRateBps()
	})
}

// SetRewardAmount sets the "reward_amount" field.
func (u *ReferralRewardUpsertBulk) SetRewardAmount(v int64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetRewardAmount(v)
	})
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *ReferralRewardUpsertBulk) AddRewardAmount(v int64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddRewardAmount(v)
	})
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateRewardAmount() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateRewardAmount()
	})
}

// SetStatus sets the "status" field.
func (u *ReferralRewardUpsertBulk) SetStatus(v referralreward.Status) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateStatus() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateStatus()
	})
}

// SetAvailableAt sets the "available_at" field.
func (u *ReferralRewardUpsertBulk) SetAvailableAt(v time.Time) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetAvailableAt(v)
	})
}

// UpdateAvailableAt sets the "available_at" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateAvailableAt() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateAvailableAt()
	})
}

// SetCreditedAt sets the "credited_at" field.
func (u *ReferralRewardUpsertBulk) SetCreditedAt(v time.Time) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetCreditedAt(v)
	})
}

// UpdateCreditedAt sets the "credited_at" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateCreditedAt() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateCreditedAt()
	})
}

// ClearCreditedAt clears the value of the "credited_at" field.
func (u *ReferralRewardUpsertBulk) ClearCreditedAt() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.ClearCreditedAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ReferralRewardUpsertBulk) SetCreatedAt(v time.Time) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateCreatedAt() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *ReferralRewardUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ReferralRewardCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralRewardCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralRewardUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
