// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/is7qin/c3api/internal/ent/predicate"
	"github.com/is7qin/c3api/internal/ent/referralreward"
)

// ReferralRewardUpdate is the builder for updating ReferralReward entities.
type ReferralRewardUpdate struct {
	config
	hooks    []Hook
	mutation *ReferralRewardMutation
}

// Where appends a list predicates to the ReferralRewardUpdate builder.
func (_u *ReferralRewardUpdate) Where(ps ...predicate.ReferralReward) *ReferralRewardUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInviterID sets the "inviter_id" field.
func (_u *ReferralRewardUpdate) SetInviterID(v int64) *ReferralRewardUpdate {
	_u.mutation.ResetInviterID()
	_u.mutation.SetInviterID(v)
	return _u
}

// SetNillableInviterID sets the "inviter_id" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableInviterID(v *int64) *ReferralRewardUpdate {
	if v != nil {
		_u.SetInviterID(*v)
	}
	return _u
}

// AddInviterID adds value to the "inviter_id" field.
func (_u *ReferralRewardUpdate) AddInviterID(v int64) *ReferralRewardUpdate {
	_u.mutation.AddInviterID(v)
	return _u
}

// SetInviteeID sets the "invitee_id" field.
func (_u *ReferralRewardUpdate) SetInviteeID(v int64) *ReferralRewardUpdate {
	_u.mutation.ResetInviteeID()
	_u.mutation.SetInviteeID(v)
	return _u
}

// SetNillableInviteeID sets the "invitee_id" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableInviteeID(v *int64) *ReferralRewardUpdate {
	if v != nil {
		_u.SetInviteeID(*v)
	}
	return _u
}

// AddInviteeID adds value to the "invitee_id" field.
func (_u *ReferralRewardUpdate) AddInviteeID(v int64) *ReferralRewardUpdate {
	_u.mutation.AddInviteeID(v)
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *ReferralRewardUpdate) SetSourceType(v referralreward.SourceType) *ReferralRewardUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableSourceType(v *referralreward.SourceType) *ReferralRewardUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *ReferralRewardUpdate) SetSourceID(v string) *ReferralRewardUpdate {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableSourceID(v *string) *ReferralRewardUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *ReferralRewardUpdate) SetIdempotencyKey(v string) *ReferralRewardUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableIdempotencyKey(v *string) *ReferralRewardUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// SetBaseAmount sets the "base_amount" field.
func (_u *ReferralRewardUpdate) SetBaseAmount(v int64) *ReferralRewardUpdate {
	_u.mutation.ResetBaseAmount()
	_u.mutation.SetBaseAmount(v)
	return _u
}

// SetNillableBaseAmount sets the "base_amount" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableBaseAmount(v *int64) *ReferralRewardUpdate {
	if v != nil {
		_u.SetBaseAmount(*v)
	}
	return _u
}

// AddBaseAmount adds value to the "base_amount" field.
func (_u *ReferralRewardUpdate) AddBaseAmount(v int64) *ReferralRewardUpdate {
	_u.mutation.AddBaseAmount(v)
	return _u
}

// SetRateBps sets the "rate_bps" field.
func (_u *ReferralRewardUpdate) SetRateBps(v int) *ReferralRewardUpdate {
	_u.mutation.ResetRateBps()
	_u.mutation.SetRateBps(v)
	return _u
}

// SetNillableRateBps sets the "rate_bps" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableRateBps(v *int) *ReferralRewardUpdate {
	if v != nil {
		_u.SetRateBps(*v)
	}
	return _u
}

// AddRateBps adds value to the "rate_bps" field.
func (_u *ReferralRewardUpdate) AddRateBps(v int) *ReferralRewardUpdate {
	_u.mutation.AddRateBps(v)
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *ReferralRewardUpdate) SetRewardAmount(v int64) *ReferralRewardUpdate {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableRewardAmount(v *int64) *ReferralRewardUpdate {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *ReferralRewardUpdate) AddRewardAmount(v int64) *ReferralRewardUpdate {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReferralRewardUpdate) SetStatus(v referralreward.Status) *ReferralRewardUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableStatus(v *referralreward.Status) *ReferralRewardUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAvailableAt sets the "available_at" field.
func (_u *ReferralRewardUpdate) SetAvailableAt(v time.Time) *ReferralRewardUpdate {
	_u.mutation.SetAvailableAt(v)
	return _u
}

// SetNillableAvailableAt sets the "available_at" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableAvailableAt(v *time.Time) *ReferralRewardUpdate {
	if v != nil {
		_u.SetAvailableAt(*v)
	}
	return _u
}

// SetCreditedAt sets the "credited_at" field.
func (_u *ReferralRewardUpdate) SetCreditedAt(v time.Time) *ReferralRewardUpdate {
	_u.mutation.SetCreditedAt(v)
	return _u
}

// SetNillableCreditedAt sets the "credited_at" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableCreditedAt(v *time.Time) *ReferralRewardUpdate {
	if v != nil {
		_u.SetCreditedAt(*v)
	}
	return _u
}

// ClearCreditedAt clears the value of the "credited_at" field.
func (_u *ReferralRewardUpdate) ClearCreditedAt() *ReferralRewardUpdate {
	_u.mutation.ClearCreditedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ReferralRewardUpdate) SetCreatedAt(v time.Time) *ReferralRewardUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableCreatedAt(v *time.Time) *ReferralRewardUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the ReferralRewardMutation object of the builder.
func (_u *ReferralRewardUpdate) Mutation() *ReferralRewardMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReferralRewardUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralRewardUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReferralRewardUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralRewardUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReferralRewardUpdate) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := referralreward.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "ReferralReward.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := referralreward.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReferralReward.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ReferralRewardUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(referralreward.Table, referralreward.Columns, sqlgraph.NewFieldSpec(referralreward.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InviterID(); ok {
		_spec.SetField(referralreward.FieldInviterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviterID(); ok {
		_spec.AddField(referralreward.FieldInviterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InviteeID(); ok {
		_spec.SetField(referralreward.FieldInviteeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviteeID(); ok {
		_spec.AddField(referralreward.FieldInviteeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(referralreward.FieldSourceType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(referralreward.FieldSourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(referralreward.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseAmount(); ok {
		_spec.SetField(referralreward.FieldBaseAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBaseAmount(); ok {
		_spec.AddField(referralreward.FieldBaseAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RateBps(); ok {
		_spec.SetField(referralreward.FieldRateBps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRateBps(); ok {
		_spec.AddField(referralreward.FieldRateBps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(referralreward.FieldRewardAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(referralreward.FieldRewardAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(referralreward.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AvailableAt(); ok {
		_spec.SetField(referralreward.FieldAvailableAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreditedAt(); ok {
		_spec.SetField(referralreward.FieldCreditedAt, field.TypeTime, value)
	}
	if _u.mutation.CreditedAtCleared() {
		_spec.ClearField(referralreward.FieldCreditedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(referralreward.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralreward.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReferralRewardUpdateOne is the builder for updating a single ReferralReward entity.
type ReferralRewardUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReferralRewardMutation
}

// SetInviterID sets the "inviter_id" field.
func (_u *ReferralRewardUpdateOne) SetInviterID(v int64) *ReferralRewardUpdateOne {
	_u.mutation.ResetInviterID()
	_u.mutation.SetInviterID(v)
	return _u
}

// SetNillableInviterID sets the "inviter_id" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableInviterID(v *int64) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetInviterID(*v)
	}
	return _u
}

// AddInviterID adds value to the "inviter_id" field.
func (_u *ReferralRewardUpdateOne) AddInviterID(v int64) *ReferralRewardUpdateOne {
	_u.mutation.AddInviterID(v)
	return _u
}

// SetInviteeID sets the "invitee_id" field.
func (_u *ReferralRewardUpdateOne) SetInviteeID(v int64) *ReferralRewardUpdateOne {
	_u.mutation.ResetInviteeID()
	_u.mutation.SetInviteeID(v)
	return _u
}

// SetNillableInviteeID sets the "invitee_id" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableInviteeID(v *int64) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetInviteeID(*v)
	}
	return _u
}

// AddInviteeID adds value to the "invitee_id" field.
func (_u *ReferralRewardUpdateOne) AddInviteeID(v int64) *ReferralRewardUpdateOne {
	_u.mutation.AddInviteeID(v)
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *ReferralRewardUpdateOne) SetSourceType(v referralreward.SourceType) *ReferralRewardUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableSourceType(v *referralreward.SourceType) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *ReferralRewardUpdateOne) SetSourceID(v string) *ReferralRewardUpdateOne {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableSourceID(v *string) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *ReferralRewardUpdateOne) SetIdempotencyKey(v string) *ReferralRewardUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableIdempotencyKey(v *string) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// SetBaseAmount sets the "base_amount" field.
func (_u *ReferralRewardUpdateOne) SetBaseAmount(v int64) *ReferralRewardUpdateOne {
	_u.mutation.ResetBaseAmount()
	_u.mutation.SetBaseAmount(v)
	return _u
}

// SetNillableBaseAmount sets the "base_amount" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableBaseAmount(v *int64) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetBaseAmount(*v)
	}
	return _u
}

// AddBaseAmount adds value to the "base_amount" field.
func (_u *ReferralRewardUpdateOne) AddBaseAmount(v int64) *ReferralRewardUpdateOne {
	_u.mutation.AddBaseAmount(v)
	return _u
}

// SetRateBps sets the "rate_bps" field.
func (_u *ReferralRewardUpdateOne) SetRateBps(v int) *ReferralRewardUpdateOne {
	_u.mutation.ResetRateBps()
	_u.mutation.SetRateBps(v)
	return _u
}

// SetNillableRateBps sets the "rate_bps" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableRateBps(v *int) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetRateBps(*v)
	}
	return _u
}

// AddRateBps adds value to the "rate_bps" field.
func (_u *ReferralRewardUpdateOne) AddRateBps(v int) *ReferralRewardUpdateOne {
	_u.mutation.AddRateBps(v)
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *ReferralRewardUpdateOne) SetRewardAmount(v int64) *ReferralRewardUpdateOne {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableRewardAmount(v *int64) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *ReferralRewardUpdateOne) AddRewardAmount(v int64) *ReferralRewardUpdateOne {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReferralRewardUpdateOne) SetStatus(v referralreward.Status) *ReferralRewardUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableStatus(v *referralreward.Status) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAvailableAt sets the "available_at" field.
func (_u *ReferralRewardUpdateOne) SetAvailableAt(v time.Time) *ReferralRewardUpdateOne {
	_u.mutation.SetAvailableAt(v)
	return _u
}

// SetNillableAvailableAt sets the "available_at" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableAvailableAt(v *time.Time) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetAvailableAt(*v)
	}
	return _u
}

// SetCreditedAt sets the "credited_at" field.
func (_u *ReferralRewardUpdateOne) SetCreditedAt(v time.Time) *ReferralRewardUpdateOne {
	_u.mutation.SetCreditedAt(v)
	return _u
}

// SetNillableCreditedAt sets the "credited_at" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableCreditedAt(v *time.Time) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetCreditedAt(*v)
	}
	return _u
}

// ClearCreditedAt clears the value of the "credited_at" field.
func (_u *ReferralRewardUpdateOne) ClearCreditedAt() *ReferralRewardUpdateOne {
	_u.mutation.ClearCreditedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ReferralRewardUpdateOne) SetCreatedAt(v time.Time) *ReferralRewardUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableCreatedAt(v *time.Time) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the ReferralRewardMutation object of the builder.
func (_u *ReferralRewardUpdateOne) Mutation() *ReferralRewardMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReferralRewardUpdate builder.
func (_u *ReferralRewardUpdateOne) Where(ps ...predicate.ReferralReward) *ReferralRewardUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReferralRewardUpdateOne) Select(field string, fields ...string) *ReferralRewardUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReferralReward entity.
func (_u *ReferralRewardUpdateOne) Save(ctx context.Context) (*ReferralReward, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralRewardUpdateOne) SaveX(ctx context.Context) *ReferralReward {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReferralRewardUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralRewardUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReferralRewardUpdateOne) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := referralreward.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "ReferralReward.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := referralreward.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReferralReward.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ReferralRewardUpdateOne) sqlSave(ctx context.Context) (_node *ReferralReward, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(referralreward.Table, referralreward.Columns, sqlgraph.NewFieldSpec(referralreward.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReferralReward.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, referralreward.FieldID)
		for _, f := range fields {
			if !referralreward.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != referralreward.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InviterID(); ok {
		_spec.SetField(referralreward.FieldInviterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviterID(); ok {
		_spec.AddField(referralreward.FieldInviterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InviteeID(); ok {
		_spec.SetField(referralreward.FieldInviteeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviteeID(); ok {
		_spec.AddField(referralreward.FieldInviteeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(referralreward.FieldSourceType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(referralreward.FieldSourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(referralreward.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseAmount(); ok {
		_spec.SetField(referralreward.FieldBaseAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBaseAmount(); ok {
		_spec.AddField(referralreward.FieldBaseAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RateBps(); ok {
		_spec.SetField(referralreward.FieldRateBps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRateBps(); ok {
		_spec.AddField(referralreward.FieldRateBps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(referralreward.FieldRewardAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(referralreward.FieldRewardAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(referralreward.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AvailableAt(); ok {
		_spec.SetField(referralreward.FieldAvailableAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreditedAt(); ok {
		_spec.SetField(referralreward.FieldCreditedAt, field.TypeTime, value)
	}
	if _u.mutation.CreditedAtCleared() {
		_spec.ClearField(referralreward.FieldCreditedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(referralreward.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &ReferralReward{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralreward.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
