// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"github.com/is7qin/c3api/internal/ent/predicate"
	"github.com/is7qin/c3api/internal/ent/templateext"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TemplateExtDelete is the builder for deleting a TemplateExt entity.
type TemplateExtDelete struct {
	config
	hooks    []Hook
	mutation *TemplateExtMutation
}

// Where appends a list predicates to the TemplateExtDelete builder.
func (_d *TemplateExtDelete) Where(ps ...predicate.TemplateExt) *TemplateExtDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TemplateExtDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TemplateExtDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TemplateExtDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(templateext.Table, sqlgraph.NewFieldSpec(templateext.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TemplateExtDeleteOne is the builder for deleting a single TemplateExt entity.
type TemplateExtDeleteOne struct {
	_d *TemplateExtDelete
}

// Where appends a list predicates to the TemplateExtDelete builder.
func (_d *TemplateExtDeleteOne) Where(ps ...predicate.TemplateExt) *TemplateExtDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TemplateExtDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{templateext.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TemplateExtDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
