// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/is7qin/c3api/internal/ent/predicate"
	"github.com/is7qin/c3api/internal/ent/template"
	"github.com/is7qin/c3api/internal/ent/templateext"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TemplateExtUpdate is the builder for updating TemplateExt entities.
type TemplateExtUpdate struct {
	config
	hooks    []Hook
	mutation *TemplateExtMutation
}

// Where appends a list predicates to the TemplateExtUpdate builder.
func (_u *TemplateExtUpdate) Where(ps ...predicate.TemplateExt) *TemplateExtUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *TemplateExtUpdate) SetTemplateID(v int64) *TemplateExtUpdate {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *TemplateExtUpdate) SetNillableTemplateID(v *int64) *TemplateExtUpdate {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// SetCredentialType sets the "credential_type" field.
func (_u *TemplateExtUpdate) SetCredentialType(v string) *TemplateExtUpdate {
	_u.mutation.SetCredentialType(v)
	return _u
}

// SetNillableCredentialType sets the "credential_type" field if the given value is not nil.
func (_u *TemplateExtUpdate) SetNillableCredentialType(v *string) *TemplateExtUpdate {
	if v != nil {
		_u.SetCredentialType(*v)
	}
	return _u
}

// SetStripImageTools sets the "strip_image_tools" field.
func (_u *TemplateExtUpdate) SetStripImageTools(v bool) *TemplateExtUpdate {
	_u.mutation.SetStripImageTools(v)
	return _u
}

// SetNillableStripImageTools sets the "strip_image_tools" field if the given value is not nil.
func (_u *TemplateExtUpdate) SetNillableStripImageTools(v *bool) *TemplateExtUpdate {
	if v != nil {
		_u.SetStripImageTools(*v)
	}
	return _u
}

// ClearStripImageTools clears the value of the "strip_image_tools" field.
func (_u *TemplateExtUpdate) ClearStripImageTools() *TemplateExtUpdate {
	_u.mutation.ClearStripImageTools()
	return _u
}

// SetTemplate sets the "template" edge to the Template entity.
func (_u *TemplateExtUpdate) SetTemplate(v *Template) *TemplateExtUpdate {
	return _u.SetTemplateID(v.ID)
}

// Mutation returns the TemplateExtMutation object of the builder.
func (_u *TemplateExtUpdate) Mutation() *TemplateExtMutation {
	return _u.mutation
}

// ClearTemplate clears the "template" edge to the Template entity.
func (_u *TemplateExtUpdate) ClearTemplate() *TemplateExtUpdate {
	_u.mutation.ClearTemplate()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TemplateExtUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TemplateExtUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TemplateExtUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TemplateExtUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TemplateExtUpdate) check() error {
	if _u.mutation.TemplateCleared() && len(_u.mutation.TemplateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TemplateExt.template"`)
	}
	return nil
}

func (_u *TemplateExtUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(templateext.Table, templateext.Columns, sqlgraph.NewFieldSpec(templateext.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CredentialType(); ok {
		_spec.SetField(templateext.FieldCredentialType, field.TypeString, value)
	}
	if value, ok := _u.mutation.StripImageTools(); ok {
		_spec.SetField(templateext.FieldStripImageTools, field.TypeBool, value)
	}
	if _u.mutation.StripImageToolsCleared() {
		_spec.ClearField(templateext.FieldStripImageTools, field.TypeBool)
	}
	if _u.mutation.TemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   templateext.TemplateTable,
			Columns: []string{templateext.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   templateext.TemplateTable,
			Columns: []string{templateext.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{templateext.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TemplateExtUpdateOne is the builder for updating a single TemplateExt entity.
type TemplateExtUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TemplateExtMutation
}

// SetTemplateID sets the "template_id" field.
func (_u *TemplateExtUpdateOne) SetTemplateID(v int64) *TemplateExtUpdateOne {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *TemplateExtUpdateOne) SetNillableTemplateID(v *int64) *TemplateExtUpdateOne {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// SetCredentialType sets the "credential_type" field.
func (_u *TemplateExtUpdateOne) SetCredentialType(v string) *TemplateExtUpdateOne {
	_u.mutation.SetCredentialType(v)
	return _u
}

// SetNillableCredentialType sets the "credential_type" field if the given value is not nil.
func (_u *TemplateExtUpdateOne) SetNillableCredentialType(v *string) *TemplateExtUpdateOne {
	if v != nil {
		_u.SetCredentialType(*v)
	}
	return _u
}

// SetStripImageTools sets the "strip_image_tools" field.
func (_u *TemplateExtUpdateOne) SetStripImageTools(v bool) *TemplateExtUpdateOne {
	_u.mutation.SetStripImageTools(v)
	return _u
}

// SetNillableStripImageTools sets the "strip_image_tools" field if the given value is not nil.
func (_u *TemplateExtUpdateOne) SetNillableStripImageTools(v *bool) *TemplateExtUpdateOne {
	if v != nil {
		_u.SetStripImageTools(*v)
	}
	return _u
}

// ClearStripImageTools clears the value of the "strip_image_tools" field.
func (_u *TemplateExtUpdateOne) ClearStripImageTools() *TemplateExtUpdateOne {
	_u.mutation.ClearStripImageTools()
	return _u
}

// SetTemplate sets the "template" edge to the Template entity.
func (_u *TemplateExtUpdateOne) SetTemplate(v *Template) *TemplateExtUpdateOne {
	return _u.SetTemplateID(v.ID)
}

// Mutation returns the TemplateExtMutation object of the builder.
func (_u *TemplateExtUpdateOne) Mutation() *TemplateExtMutation {
	return _u.mutation
}

// ClearTemplate clears the "template" edge to the Template entity.
func (_u *TemplateExtUpdateOne) ClearTemplate() *TemplateExtUpdateOne {
	_u.mutation.ClearTemplate()
	return _u
}

// Where appends a list predicates to the TemplateExtUpdate builder.
func (_u *TemplateExtUpdateOne) Where(ps ...predicate.TemplateExt) *TemplateExtUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TemplateExtUpdateOne) Select(field string, fields ...string) *TemplateExtUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TemplateExt entity.
func (_u *TemplateExtUpdateOne) Save(ctx context.Context) (*TemplateExt, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TemplateExtUpdateOne) SaveX(ctx context.Context) *TemplateExt {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TemplateExtUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TemplateExtUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TemplateExtUpdateOne) check() error {
	if _u.mutation.TemplateCleared() && len(_u.mutation.TemplateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TemplateExt.template"`)
	}
	return nil
}

func (_u *TemplateExtUpdateOne) sqlSave(ctx context.Context) (_node *TemplateExt, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(templateext.Table, templateext.Columns, sqlgraph.NewFieldSpec(templateext.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TemplateExt.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, templateext.FieldID)
		for _, f := range fields {
			if !templateext.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != templateext.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CredentialType(); ok {
		_spec.SetField(templateext.FieldCredentialType, field.TypeString, value)
	}
	if value, ok := _u.mutation.StripImageTools(); ok {
		_spec.SetField(templateext.FieldStripImageTools, field.TypeBool, value)
	}
	if _u.mutation.StripImageToolsCleared() {
		_spec.ClearField(templateext.FieldStripImageTools, field.TypeBool)
	}
	if _u.mutation.TemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   templateext.TemplateTable,
			Columns: []string{templateext.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   templateext.TemplateTable,
			Columns: []string{templateext.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TemplateExt{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{templateext.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
