// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-proxy-mini/internal/ent/usagelog"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UsageLogCreate is the builder for creating a UsageLog entity.
type UsageLogCreate struct {
	config
	mutation *UsageLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRequestID sets the "request_id" field.
func (_c *UsageLogCreate) SetRequestID(v string) *UsageLogCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *UsageLogCreate) SetGroupID(v int64) *UsageLogCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableGroupID(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *UsageLogCreate) SetAccountID(v int64) *UsageLogCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableAccountID(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetTemplateID sets the "template_id" field.
func (_c *UsageLogCreate) SetTemplateID(v int64) *UsageLogCreate {
	_c.mutation.SetTemplateID(v)
	return _c
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableTemplateID(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetTemplateID(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *UsageLogCreate) SetModel(v string) *UsageLogCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableModel(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetMappedModel sets the "mapped_model" field.
func (_c *UsageLogCreate) SetMappedModel(v string) *UsageLogCreate {
	_c.mutation.SetMappedModel(v)
	return _c
}

// SetNillableMappedModel sets the "mapped_model" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableMappedModel(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetMappedModel(*v)
	}
	return _c
}

// SetFormat sets the "format" field.
func (_c *UsageLogCreate) SetFormat(v usagelog.Format) *UsageLogCreate {
	_c.mutation.SetFormat(v)
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *UsageLogCreate) SetStatusCode(v int) *UsageLogCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableStatusCode(v *int) *UsageLogCreate {
	if v != nil {
		_c.SetStatusCode(*v)
	}
	return _c
}

// SetErrorType sets the "error_type" field.
func (_c *UsageLogCreate) SetErrorType(v string) *UsageLogCreate {
	_c.mutation.SetErrorType(v)
	return _c
}

// SetNillableErrorType sets the "error_type" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableErrorType(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetErrorType(*v)
	}
	return _c
}

// SetLatencyMs sets the "latency_ms" field.
func (_c *UsageLogCreate) SetLatencyMs(v int64) *UsageLogCreate {
	_c.mutation.SetLatencyMs(v)
	return _c
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableLatencyMs(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetLatencyMs(*v)
	}
	return _c
}

// SetPromptTokens sets the "prompt_tokens" field.
func (_c *UsageLogCreate) SetPromptTokens(v int64) *UsageLogCreate {
	_c.mutation.SetPromptTokens(v)
	return _c
}

// SetNillablePromptTokens sets the "prompt_tokens" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillablePromptTokens(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetPromptTokens(*v)
	}
	return _c
}

// SetCompletionTokens sets the "completion_tokens" field.
func (_c *UsageLogCreate) SetCompletionTokens(v int64) *UsageLogCreate {
	_c.mutation.SetCompletionTokens(v)
	return _c
}

// SetNillableCompletionTokens sets the "completion_tokens" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableCompletionTokens(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetCompletionTokens(*v)
	}
	return _c
}

// SetTotalTokens sets the "total_tokens" field.
func (_c *UsageLogCreate) SetTotalTokens(v int64) *UsageLogCreate {
	_c.mutation.SetTotalTokens(v)
	return _c
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableTotalTokens(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetTotalTokens(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UsageLogCreate) SetCreatedAt(v time.Time) *UsageLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableCreatedAt(v *time.Time) *UsageLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UsageLogCreate) SetID(v int64) *UsageLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UsageLogMutation object of the builder.
func (_c *UsageLogCreate) Mutation() *UsageLogMutation {
	return _c.mutation
}

// Save creates the UsageLog in the database.
func (_c *UsageLogCreate) Save(ctx context.Context) (*UsageLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UsageLogCreate) SaveX(ctx context.Context) *UsageLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UsageLogCreate) defaults() {
	if _, ok := _c.mutation.Model(); !ok {
		v := usagelog.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		v := usagelog.DefaultStatusCode
		_c.mutation.SetStatusCode(v)
	}
	if _, ok := _c.mutation.ErrorType(); !ok {
		v := usagelog.DefaultErrorType
		_c.mutation.SetErrorType(v)
	}
	if _, ok := _c.mutation.LatencyMs(); !ok {
		v := usagelog.DefaultLatencyMs
		_c.mutation.SetLatencyMs(v)
	}
	if _, ok := _c.mutation.PromptTokens(); !ok {
		v := usagelog.DefaultPromptTokens
		_c.mutation.SetPromptTokens(v)
	}
	if _, ok := _c.mutation.CompletionTokens(); !ok {
		v := usagelog.DefaultCompletionTokens
		_c.mutation.SetCompletionTokens(v)
	}
	if _, ok := _c.mutation.TotalTokens(); !ok {
		v := usagelog.DefaultTotalTokens
		_c.mutation.SetTotalTokens(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usagelog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UsageLogCreate) check() error {
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "UsageLog.request_id"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "UsageLog.model"`)}
	}
	if _, ok := _c.mutation.Format(); !ok {
		return &ValidationError{Name: "format", err: errors.New(`ent: missing required field "UsageLog.format"`)}
	}
	if v, ok := _c.mutation.Format(); ok {
		if err := usagelog.FormatValidator(v); err != nil {
			return &ValidationError{Name: "format", err: fmt.Errorf(`ent: validator failed for field "UsageLog.format": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		return &ValidationError{Name: "status_code", err: errors.New(`ent: missing required field "UsageLog.status_code"`)}
	}
	if _, ok := _c.mutation.ErrorType(); !ok {
		return &ValidationError{Name: "error_type", err: errors.New(`ent: missing required field "UsageLog.error_type"`)}
	}
	if _, ok := _c.mutation.LatencyMs(); !ok {
		return &ValidationError{Name: "latency_ms", err: errors.New(`ent: missing required field "UsageLog.latency_ms"`)}
	}
	if _, ok := _c.mutation.PromptTokens(); !ok {
		return &ValidationError{Name: "prompt_tokens", err: errors.New(`ent: missing required field "UsageLog.prompt_tokens"`)}
	}
	if _, ok := _c.mutation.CompletionTokens(); !ok {
		return &ValidationError{Name: "completion_tokens", err: errors.New(`ent: missing required field "UsageLog.completion_tokens"`)}
	}
	if _, ok := _c.mutation.TotalTokens(); !ok {
		return &ValidationError{Name: "total_tokens", err: errors.New(`ent: missing required field "UsageLog.total_tokens"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UsageLog.created_at"`)}
	}
	return nil
}

func (_c *UsageLogCreate) sqlSave(ctx context.Context) (*UsageLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UsageLogCreate) createSpec() (*UsageLog, *sqlgraph.CreateSpec) {
	var (
		_node = &UsageLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usagelog.Table, sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(usagelog.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(usagelog.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(usagelog.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = &value
	}
	if value, ok := _c.mutation.TemplateID(); ok {
		_spec.SetField(usagelog.FieldTemplateID, field.TypeInt64, value)
		_node.TemplateID = &value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(usagelog.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.MappedModel(); ok {
		_spec.SetField(usagelog.FieldMappedModel, field.TypeString, value)
		_node.MappedModel = &value
	}
	if value, ok := _c.mutation.Format(); ok {
		_spec.SetField(usagelog.FieldFormat, field.TypeEnum, value)
		_node.Format = value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(usagelog.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = value
	}
	if value, ok := _c.mutation.ErrorType(); ok {
		_spec.SetField(usagelog.FieldErrorType, field.TypeString, value)
		_node.ErrorType = value
	}
	if value, ok := _c.mutation.LatencyMs(); ok {
		_spec.SetField(usagelog.FieldLatencyMs, field.TypeInt64, value)
		_node.LatencyMs = value
	}
	if value, ok := _c.mutation.PromptTokens(); ok {
		_spec.SetField(usagelog.FieldPromptTokens, field.TypeInt64, value)
		_node.PromptTokens = value
	}
	if value, ok := _c.mutation.CompletionTokens(); ok {
		_spec.SetField(usagelog.FieldCompletionTokens, field.TypeInt64, value)
		_node.CompletionTokens = value
	}
	if value, ok := _c.mutation.TotalTokens(); ok {
		_spec.SetField(usagelog.FieldTotalTokens, field.TypeInt64, value)
		_node.TotalTokens = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usagelog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageLog.Create().
//		SetRequestID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageLogUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageLogCreate) OnConflict(opts ...sql.ConflictOption) *UsageLogUpsertOne {
	_c.conflict = opts
	return &UsageLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageLogCreate) OnConflictColumns(columns ...string) *UsageLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageLogUpsertOne{
		create: _c,
	}
}

type (
	// UsageLogUpsertOne is the builder for "upsert"-ing
	//  one UsageLog node.
	UsageLogUpsertOne struct {
		create *UsageLogCreate
	}

	// UsageLogUpsert is the "OnConflict" setter.
	UsageLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetRequestID sets the "request_id" field.
func (u *UsageLogUpsert) SetRequestID(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateRequestID() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldRequestID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *UsageLogUpsert) SetGroupID(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateGroupID() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *UsageLogUpsert) AddGroupID(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *UsageLogUpsert) ClearGroupID() *UsageLogUpsert {
	u.SetNull(usagelog.FieldGroupID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *UsageLogUpsert) SetAccountID(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateAccountID() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *UsageLogUpsert) AddAccountID(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldAccountID, v)
	return u
}

// ClearAccountID clears the value of the "account_id" field.
func (u *UsageLogUpsert) ClearAccountID() *UsageLogUpsert {
	u.SetNull(usagelog.FieldAccountID)
	return u
}

// SetTemplateID sets the "template_id" field.
func (u *UsageLogUpsert) SetTemplateID(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldTemplateID, v)
	return u
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateTemplateID() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldTemplateID)
	return u
}

// AddTemplateID adds v to the "template_id" field.
func (u *UsageLogUpsert) AddTemplateID(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldTemplateID, v)
	return u
}

// ClearTemplateID clears the value of the "template_id" field.
func (u *UsageLogUpsert) ClearTemplateID() *UsageLogUpsert {
	u.SetNull(usagelog.FieldTemplateID)
	return u
}

// SetModel sets the "model" field.
func (u *UsageLogUpsert) SetModel(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateModel() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldModel)
	return u
}

// SetMappedModel sets the "mapped_model" field.
func (u *UsageLogUpsert) SetMappedModel(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldMappedModel, v)
	return u
}

// UpdateMappedModel sets the "mapped_model" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateMappedModel() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldMappedModel)
	return u
}

// ClearMappedModel clears the value of the "mapped_model" field.
func (u *UsageLogUpsert) ClearMappedModel() *UsageLogUpsert {
	u.SetNull(usagelog.FieldMappedModel)
	return u
}

// SetFormat sets the "format" field.
func (u *UsageLogUpsert) SetFormat(v usagelog.Format) *UsageLogUpsert {
	u.Set(usagelog.FieldFormat, v)
	return u
}

// UpdateFormat sets the "format" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateFormat() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldFormat)
	return u
}

// SetStatusCode sets the "status_code" field.
func (u *UsageLogUpsert) SetStatusCode(v int) *UsageLogUpsert {
	u.Set(usagelog.FieldStatusCode, v)
	return u
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateStatusCode() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldStatusCode)
	return u
}

// AddStatusCode adds v to the "status_code" field.
func (u *UsageLogUpsert) AddStatusCode(v int) *UsageLogUpsert {
	u.Add(usagelog.FieldStatusCode, v)
	return u
}

// SetErrorType sets the "error_type" field.
func (u *UsageLogUpsert) SetErrorType(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldErrorType, v)
	return u
}

// UpdateErrorType sets the "error_type" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateErrorType() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldErrorType)
	return u
}

// SetLatencyMs sets the "latency_ms" field.
func (u *UsageLogUpsert) SetLatencyMs(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldLatencyMs, v)
	return u
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateLatencyMs() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldLatencyMs)
	return u
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *UsageLogUpsert) AddLatencyMs(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldLatencyMs, v)
	return u
}

// SetPromptTokens sets the "prompt_tokens" field.
func (u *UsageLogUpsert) SetPromptTokens(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldPromptTokens, v)
	return u
}

// UpdatePromptTokens sets the "prompt_tokens" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdatePromptTokens() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldPromptTokens)
	return u
}

// AddPromptTokens adds v to the "prompt_tokens" field.
func (u *UsageLogUpsert) AddPromptTokens(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldPromptTokens, v)
	return u
}

// SetCompletionTokens sets the "completion_tokens" field.
func (u *UsageLogUpsert) SetCompletionTokens(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldCompletionTokens, v)
	return u
}

// UpdateCompletionTokens sets the "completion_tokens" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateCompletionTokens() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldCompletionTokens)
	return u
}

// AddCompletionTokens adds v to the "completion_tokens" field.
func (u *UsageLogUpsert) AddCompletionTokens(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldCompletionTokens, v)
	return u
}

// SetTotalTokens sets the "total_tokens" field.
func (u *UsageLogUpsert) SetTotalTokens(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldTotalTokens, v)
	return u
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateTotalTokens() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldTotalTokens)
	return u
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *UsageLogUpsert) AddTotalTokens(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldTotalTokens, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *UsageLogUpsert) SetCreatedAt(v time.Time) *UsageLogUpsert {
	u.Set(usagelog.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateCreatedAt() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UsageLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(usagelog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UsageLogUpsertOne) UpdateNewValues() *UsageLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(usagelog.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UsageLogUpsertOne) Ignore() *UsageLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageLogUpsertOne) DoNothing() *UsageLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageLogCreate.OnConflict
// documentation for more info.
func (u *UsageLogUpsertOne) Update(set func(*UsageLogUpsert)) *UsageLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *UsageLogUpsertOne) SetRequestID(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateRequestID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateRequestID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UsageLogUpsertOne) SetGroupID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *UsageLogUpsertOne) AddGroupID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateGroupID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *UsageLogUpsertOne) ClearGroupID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *UsageLogUpsertOne) SetAccountID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *UsageLogUpsertOne) AddAccountID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateAccountID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *UsageLogUpsertOne) ClearAccountID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearAccountID()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *UsageLogUpsertOne) SetTemplateID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetTemplateID(v)
	})
}

// AddTemplateID adds v to the "template_id" field.
func (u *UsageLogUpsertOne) AddTemplateID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateTemplateID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateTemplateID()
	})
}

// ClearTemplateID clears the value of the "template_id" field.
func (u *UsageLogUpsertOne) ClearTemplateID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearTemplateID()
	})
}

// SetModel sets the "model" field.
func (u *UsageLogUpsertOne) SetModel(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateModel() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateModel()
	})
}

// SetMappedModel sets the "mapped_model" field.
func (u *UsageLogUpsertOne) SetMappedModel(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetMappedModel(v)
	})
}

// UpdateMappedModel sets the "mapped_model" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateMappedModel() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateMappedModel()
	})
}

// ClearMappedModel clears the value of the "mapped_model" field.
func (u *UsageLogUpsertOne) ClearMappedModel() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearMappedModel()
	})
}

// SetFormat sets the "format" field.
func (u *UsageLogUpsertOne) SetFormat(v usagelog.Format) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetFormat(v)
	})
}

// UpdateFormat sets the "format" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateFormat() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateFormat()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *UsageLogUpsertOne) SetStatusCode(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *UsageLogUpsertOne) AddStatusCode(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateStatusCode() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateStatusCode()
	})
}

// SetErrorType sets the "error_type" field.
func (u *UsageLogUpsertOne) SetErrorType(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetErrorType(v)
	})
}

// UpdateErrorType sets the "error_type" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateErrorType() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateErrorType()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *UsageLogUpsertOne) SetLatencyMs(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *UsageLogUpsertOne) AddLatencyMs(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateLatencyMs() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateLatencyMs()
	})
}

// SetPromptTokens sets the "prompt_tokens" field.
func (u *UsageLogUpsertOne) SetPromptTokens(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetPromptTokens(v)
	})
}

// AddPromptTokens adds v to the "prompt_tokens" field.
func (u *UsageLogUpsertOne) AddPromptTokens(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddPromptTokens(v)
	})
}

// UpdatePromptTokens sets the "prompt_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdatePromptTokens() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdatePromptTokens()
	})
}

// SetCompletionTokens sets the "completion_tokens" field.
func (u *UsageLogUpsertOne) SetCompletionTokens(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCompletionTokens(v)
	})
}

// AddCompletionTokens adds v to the "completion_tokens" field.
func (u *UsageLogUpsertOne) AddCompletionTokens(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddCompletionTokens(v)
	})
}

// UpdateCompletionTokens sets the "completion_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateCompletionTokens() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCompletionTokens()
	})
}

// SetTotalTokens sets the "total_tokens" field.
func (u *UsageLogUpsertOne) SetTotalTokens(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetTotalTokens(v)
	})
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *UsageLogUpsertOne) AddTotalTokens(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddTotalTokens(v)
	})
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateTotalTokens() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateTotalTokens()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *UsageLogUpsertOne) SetCreatedAt(v time.Time) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateCreatedAt() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *UsageLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UsageLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UsageLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UsageLogCreateBulk is the builder for creating many UsageLog entities in bulk.
type UsageLogCreateBulk struct {
	config
	err      error
	builders []*UsageLogCreate
	conflict []sql.ConflictOption
}

// Save creates the UsageLog entities in the database.
func (_c *UsageLogCreateBulk) Save(ctx context.Context) ([]*UsageLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UsageLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsageLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UsageLogCreateBulk) SaveX(ctx context.Context) []*UsageLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageLogUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *UsageLogUpsertBulk {
	_c.conflict = opts
	return &UsageLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageLogCreateBulk) OnConflictColumns(columns ...string) *UsageLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageLogUpsertBulk{
		create: _c,
	}
}

// UsageLogUpsertBulk is the builder for "upsert"-ing
// a bulk of UsageLog nodes.
type UsageLogUpsertBulk struct {
	create *UsageLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UsageLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(usagelog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UsageLogUpsertBulk) UpdateNewValues() *UsageLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(usagelog.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UsageLogUpsertBulk) Ignore() *UsageLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageLogUpsertBulk) DoNothing() *UsageLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageLogCreateBulk.OnConflict
// documentation for more info.
func (u *UsageLogUpsertBulk) Update(set func(*UsageLogUpsert)) *UsageLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *UsageLogUpsertBulk) SetRequestID(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateRequestID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateRequestID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UsageLogUpsertBulk) SetGroupID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *UsageLogUpsertBulk) AddGroupID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateGroupID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *UsageLogUpsertBulk) ClearGroupID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *UsageLogUpsertBulk) SetAccountID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *UsageLogUpsertBulk) AddAccountID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateAccountID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *UsageLogUpsertBulk) ClearAccountID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearAccountID()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *UsageLogUpsertBulk) SetTemplateID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetTemplateID(v)
	})
}

// AddTemplateID adds v to the "template_id" field.
func (u *UsageLogUpsertBulk) AddTemplateID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateTemplateID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateTemplateID()
	})
}

// ClearTemplateID clears the value of the "template_id" field.
func (u *UsageLogUpsertBulk) ClearTemplateID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearTemplateID()
	})
}

// SetModel sets the "model" field.
func (u *UsageLogUpsertBulk) SetModel(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateModel() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateModel()
	})
}

// SetMappedModel sets the "mapped_model" field.
func (u *UsageLogUpsertBulk) SetMappedModel(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetMappedModel(v)
	})
}

// UpdateMappedModel sets the "mapped_model" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateMappedModel() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateMappedModel()
	})
}

// ClearMappedModel clears the value of the "mapped_model" field.
func (u *UsageLogUpsertBulk) ClearMappedModel() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearMappedModel()
	})
}

// SetFormat sets the "format" field.
func (u *UsageLogUpsertBulk) SetFormat(v usagelog.Format) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetFormat(v)
	})
}

// UpdateFormat sets the "format" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateFormat() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateFormat()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *UsageLogUpsertBulk) SetStatusCode(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *UsageLogUpsertBulk) AddStatusCode(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateStatusCode() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateStatusCode()
	})
}

// SetErrorType sets the "error_type" field.
func (u *UsageLogUpsertBulk) SetErrorType(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetErrorType(v)
	})
}

// UpdateErrorType sets the "error_type" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateErrorType() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateErrorType()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *UsageLogUpsertBulk) SetLatencyMs(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *UsageLogUpsertBulk) AddLatencyMs(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateLatencyMs() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateLatencyMs()
	})
}

// SetPromptTokens sets the "prompt_tokens" field.
func (u *UsageLogUpsertBulk) SetPromptTokens(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetPromptTokens(v)
	})
}

// AddPromptTokens adds v to the "prompt_tokens" field.
func (u *UsageLogUpsertBulk) AddPromptTokens(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddPromptTokens(v)
	})
}

// UpdatePromptTokens sets the "prompt_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdatePromptTokens() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdatePromptTokens()
	})
}

// SetCompletionTokens sets the "completion_tokens" field.
func (u *UsageLogUpsertBulk) SetCompletionTokens(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCompletionTokens(v)
	})
}

// AddCompletionTokens adds v to the "completion_tokens" field.
func (u *UsageLogUpsertBulk) AddCompletionTokens(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddCompletionTokens(v)
	})
}

// UpdateCompletionTokens sets the "completion_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateCompletionTokens() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCompletionTokens()
	})
}

// SetTotalTokens sets the "total_tokens" field.
func (u *UsageLogUpsertBulk) SetTotalTokens(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetTotalTokens(v)
	})
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *UsageLogUpsertBulk) AddTotalTokens(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddTotalTokens(v)
	})
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateTotalTokens() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateTotalTokens()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *UsageLogUpsertBulk) SetCreatedAt(v time.Time) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateCreatedAt() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *UsageLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UsageLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
