// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-proxy-mini/internal/ent/usagelog"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UsageLogCreate is the builder for creating a UsageLog entity.
type UsageLogCreate struct {
	config
	mutation *UsageLogMutation
	hooks    []Hook
}

// SetRequestID sets the "request_id" field.
func (_c *UsageLogCreate) SetRequestID(v string) *UsageLogCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *UsageLogCreate) SetGroupID(v int64) *UsageLogCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableGroupID(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *UsageLogCreate) SetAccountID(v int64) *UsageLogCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableAccountID(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetTemplateID sets the "template_id" field.
func (_c *UsageLogCreate) SetTemplateID(v int64) *UsageLogCreate {
	_c.mutation.SetTemplateID(v)
	return _c
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableTemplateID(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetTemplateID(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *UsageLogCreate) SetModel(v string) *UsageLogCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableModel(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetMappedModel sets the "mapped_model" field.
func (_c *UsageLogCreate) SetMappedModel(v string) *UsageLogCreate {
	_c.mutation.SetMappedModel(v)
	return _c
}

// SetNillableMappedModel sets the "mapped_model" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableMappedModel(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetMappedModel(*v)
	}
	return _c
}

// SetFormat sets the "format" field.
func (_c *UsageLogCreate) SetFormat(v usagelog.Format) *UsageLogCreate {
	_c.mutation.SetFormat(v)
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *UsageLogCreate) SetStatusCode(v int) *UsageLogCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableStatusCode(v *int) *UsageLogCreate {
	if v != nil {
		_c.SetStatusCode(*v)
	}
	return _c
}

// SetErrorType sets the "error_type" field.
func (_c *UsageLogCreate) SetErrorType(v string) *UsageLogCreate {
	_c.mutation.SetErrorType(v)
	return _c
}

// SetNillableErrorType sets the "error_type" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableErrorType(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetErrorType(*v)
	}
	return _c
}

// SetLatencyMs sets the "latency_ms" field.
func (_c *UsageLogCreate) SetLatencyMs(v int64) *UsageLogCreate {
	_c.mutation.SetLatencyMs(v)
	return _c
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableLatencyMs(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetLatencyMs(*v)
	}
	return _c
}

// SetPromptTokens sets the "prompt_tokens" field.
func (_c *UsageLogCreate) SetPromptTokens(v int64) *UsageLogCreate {
	_c.mutation.SetPromptTokens(v)
	return _c
}

// SetNillablePromptTokens sets the "prompt_tokens" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillablePromptTokens(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetPromptTokens(*v)
	}
	return _c
}

// SetCompletionTokens sets the "completion_tokens" field.
func (_c *UsageLogCreate) SetCompletionTokens(v int64) *UsageLogCreate {
	_c.mutation.SetCompletionTokens(v)
	return _c
}

// SetNillableCompletionTokens sets the "completion_tokens" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableCompletionTokens(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetCompletionTokens(*v)
	}
	return _c
}

// SetTotalTokens sets the "total_tokens" field.
func (_c *UsageLogCreate) SetTotalTokens(v int64) *UsageLogCreate {
	_c.mutation.SetTotalTokens(v)
	return _c
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableTotalTokens(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetTotalTokens(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UsageLogCreate) SetCreatedAt(v time.Time) *UsageLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableCreatedAt(v *time.Time) *UsageLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UsageLogCreate) SetID(v int64) *UsageLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UsageLogMutation object of the builder.
func (_c *UsageLogCreate) Mutation() *UsageLogMutation {
	return _c.mutation
}

// Save creates the UsageLog in the database.
func (_c *UsageLogCreate) Save(ctx context.Context) (*UsageLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UsageLogCreate) SaveX(ctx context.Context) *UsageLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UsageLogCreate) defaults() {
	if _, ok := _c.mutation.Model(); !ok {
		v := usagelog.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		v := usagelog.DefaultStatusCode
		_c.mutation.SetStatusCode(v)
	}
	if _, ok := _c.mutation.ErrorType(); !ok {
		v := usagelog.DefaultErrorType
		_c.mutation.SetErrorType(v)
	}
	if _, ok := _c.mutation.LatencyMs(); !ok {
		v := usagelog.DefaultLatencyMs
		_c.mutation.SetLatencyMs(v)
	}
	if _, ok := _c.mutation.PromptTokens(); !ok {
		v := usagelog.DefaultPromptTokens
		_c.mutation.SetPromptTokens(v)
	}
	if _, ok := _c.mutation.CompletionTokens(); !ok {
		v := usagelog.DefaultCompletionTokens
		_c.mutation.SetCompletionTokens(v)
	}
	if _, ok := _c.mutation.TotalTokens(); !ok {
		v := usagelog.DefaultTotalTokens
		_c.mutation.SetTotalTokens(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usagelog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UsageLogCreate) check() error {
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "UsageLog.request_id"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "UsageLog.model"`)}
	}
	if _, ok := _c.mutation.Format(); !ok {
		return &ValidationError{Name: "format", err: errors.New(`ent: missing required field "UsageLog.format"`)}
	}
	if v, ok := _c.mutation.Format(); ok {
		if err := usagelog.FormatValidator(v); err != nil {
			return &ValidationError{Name: "format", err: fmt.Errorf(`ent: validator failed for field "UsageLog.format": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		return &ValidationError{Name: "status_code", err: errors.New(`ent: missing required field "UsageLog.status_code"`)}
	}
	if _, ok := _c.mutation.ErrorType(); !ok {
		return &ValidationError{Name: "error_type", err: errors.New(`ent: missing required field "UsageLog.error_type"`)}
	}
	if _, ok := _c.mutation.LatencyMs(); !ok {
		return &ValidationError{Name: "latency_ms", err: errors.New(`ent: missing required field "UsageLog.latency_ms"`)}
	}
	if _, ok := _c.mutation.PromptTokens(); !ok {
		return &ValidationError{Name: "prompt_tokens", err: errors.New(`ent: missing required field "UsageLog.prompt_tokens"`)}
	}
	if _, ok := _c.mutation.CompletionTokens(); !ok {
		return &ValidationError{Name: "completion_tokens", err: errors.New(`ent: missing required field "UsageLog.completion_tokens"`)}
	}
	if _, ok := _c.mutation.TotalTokens(); !ok {
		return &ValidationError{Name: "total_tokens", err: errors.New(`ent: missing required field "UsageLog.total_tokens"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UsageLog.created_at"`)}
	}
	return nil
}

func (_c *UsageLogCreate) sqlSave(ctx context.Context) (*UsageLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UsageLogCreate) createSpec() (*UsageLog, *sqlgraph.CreateSpec) {
	var (
		_node = &UsageLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usagelog.Table, sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(usagelog.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(usagelog.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(usagelog.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = &value
	}
	if value, ok := _c.mutation.TemplateID(); ok {
		_spec.SetField(usagelog.FieldTemplateID, field.TypeInt64, value)
		_node.TemplateID = &value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(usagelog.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.MappedModel(); ok {
		_spec.SetField(usagelog.FieldMappedModel, field.TypeString, value)
		_node.MappedModel = &value
	}
	if value, ok := _c.mutation.Format(); ok {
		_spec.SetField(usagelog.FieldFormat, field.TypeEnum, value)
		_node.Format = value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(usagelog.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = value
	}
	if value, ok := _c.mutation.ErrorType(); ok {
		_spec.SetField(usagelog.FieldErrorType, field.TypeString, value)
		_node.ErrorType = value
	}
	if value, ok := _c.mutation.LatencyMs(); ok {
		_spec.SetField(usagelog.FieldLatencyMs, field.TypeInt64, value)
		_node.LatencyMs = value
	}
	if value, ok := _c.mutation.PromptTokens(); ok {
		_spec.SetField(usagelog.FieldPromptTokens, field.TypeInt64, value)
		_node.PromptTokens = value
	}
	if value, ok := _c.mutation.CompletionTokens(); ok {
		_spec.SetField(usagelog.FieldCompletionTokens, field.TypeInt64, value)
		_node.CompletionTokens = value
	}
	if value, ok := _c.mutation.TotalTokens(); ok {
		_spec.SetField(usagelog.FieldTotalTokens, field.TypeInt64, value)
		_node.TotalTokens = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usagelog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// UsageLogCreateBulk is the builder for creating many UsageLog entities in bulk.
type UsageLogCreateBulk struct {
	config
	err      error
	builders []*UsageLogCreate
}

// Save creates the UsageLog entities in the database.
func (_c *UsageLogCreateBulk) Save(ctx context.Context) ([]*UsageLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UsageLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsageLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UsageLogCreateBulk) SaveX(ctx context.Context) []*UsageLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
