// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package handler

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AccountPatchStatus.
const (
	AccountPatchStatusActive    AccountPatchStatus = "active"
	AccountPatchStatusDisabled  AccountPatchStatus = "disabled"
	AccountPatchStatusN429      AccountPatchStatus = "429"
	AccountPatchStatusUnhealthy AccountPatchStatus = "unhealthy"
)

// Defines values for AccountStatus.
const (
	AccountStatusActive    AccountStatus = "active"
	AccountStatusDisabled  AccountStatus = "disabled"
	AccountStatusN429      AccountStatus = "429"
	AccountStatusUnhealthy AccountStatus = "unhealthy"
)

// Defines values for ErrorType.
const (
	Abort     ErrorType = "abort"
	Auth      ErrorType = "auth"
	N429      ErrorType = "429"
	N4xx      ErrorType = "4xx"
	N5xx      ErrorType = "5xx"
	Network   ErrorType = "network"
	NoAccount ErrorType = "no_account"
	None      ErrorType = "none"
)

// Defines values for RequestFormat.
const (
	RequestFormatAnthropic       RequestFormat = "anthropic"
	RequestFormatOpenaiChat      RequestFormat = "openai-chat"
	RequestFormatOpenaiResponses RequestFormat = "openai-responses"
)

// Defines values for TemplateSupportedFormats.
const (
	TemplateSupportedFormatsAnthropic       TemplateSupportedFormats = "anthropic"
	TemplateSupportedFormatsOpenaiChat      TemplateSupportedFormats = "openai-chat"
	TemplateSupportedFormatsOpenaiResponses TemplateSupportedFormats = "openai-responses"
)

// Defines values for TemplateCreateSupportedFormats.
const (
	TemplateCreateSupportedFormatsAnthropic       TemplateCreateSupportedFormats = "anthropic"
	TemplateCreateSupportedFormatsOpenaiChat      TemplateCreateSupportedFormats = "openai-chat"
	TemplateCreateSupportedFormatsOpenaiResponses TemplateCreateSupportedFormats = "openai-responses"
)

// Defines values for TemplatePatchSupportedFormats.
const (
	TemplatePatchSupportedFormatsAnthropic       TemplatePatchSupportedFormats = "anthropic"
	TemplatePatchSupportedFormatsOpenaiChat      TemplatePatchSupportedFormats = "openai-chat"
	TemplatePatchSupportedFormatsOpenaiResponses TemplatePatchSupportedFormats = "openai-responses"
)

// Defines values for GetAccountsParamsOrder.
const (
	GetAccountsParamsOrderAsc  GetAccountsParamsOrder = "asc"
	GetAccountsParamsOrderDesc GetAccountsParamsOrder = "desc"
)

// Defines values for GetGroupsParamsOrder.
const (
	GetGroupsParamsOrderAsc  GetGroupsParamsOrder = "asc"
	GetGroupsParamsOrderDesc GetGroupsParamsOrder = "desc"
)

// Defines values for GetStatsParamsGranularity.
const (
	Day  GetStatsParamsGranularity = "day"
	Hour GetStatsParamsGranularity = "hour"
)

// Defines values for GetTemplatesParamsOrder.
const (
	Asc  GetTemplatesParamsOrder = "asc"
	Desc GetTemplatesParamsOrder = "desc"
)

// Account defines model for Account.
type Account struct {
	CooldownUntil  *time.Time     `json:"CooldownUntil"`
	CreatedAt      *time.Time     `json:"CreatedAt,omitempty"`
	ID             *int64         `json:"ID,omitempty"`
	LastError      *string        `json:"LastError"`
	LastUsedAt     *time.Time     `json:"LastUsedAt"`
	MaxConcurrency *int           `json:"MaxConcurrency,omitempty"`
	Name           *string        `json:"Name,omitempty"`
	Status         *AccountStatus `json:"Status,omitempty"`
	Template       *Template      `json:"Template,omitempty"`
	TemplateID     *int64         `json:"TemplateID,omitempty"`
	UpdatedAt      *time.Time     `json:"UpdatedAt,omitempty"`
	UpstreamKey    *string        `json:"UpstreamKey,omitempty"`
	Weight         *int           `json:"Weight,omitempty"`
}

// AccountCreate defines model for AccountCreate.
type AccountCreate struct {
	MaxConcurrency *int           `json:"max_concurrency,omitempty"`
	Name           string         `json:"name"`
	Status         *AccountStatus `json:"status,omitempty"`
	TemplateId     int64          `json:"template_id"`
	UpstreamKey    string         `json:"upstream_key"`
	Weight         *int           `json:"weight,omitempty"`
}

// AccountListResponse defines model for AccountListResponse.
type AccountListResponse struct {
	Rows  []AccountView `json:"rows"`
	Total int64         `json:"total"`
}

// AccountPatch defines model for AccountPatch.
type AccountPatch struct {
	MaxConcurrency *int                `json:"max_concurrency,omitempty"`
	Name           *string             `json:"name,omitempty"`
	Status         *AccountPatchStatus `json:"status,omitempty"`
	TemplateId     *int64              `json:"template_id,omitempty"`
	UpstreamKey    *string             `json:"upstream_key,omitempty"`
	Weight         *int                `json:"weight,omitempty"`
}

// AccountPatchStatus defines model for AccountPatch.Status.
type AccountPatchStatus string

// AccountStatus defines model for AccountStatus.
type AccountStatus string

// AccountView defines model for AccountView.
type AccountView struct {
	CooldownUntil  *time.Time     `json:"CooldownUntil"`
	CreatedAt      *time.Time     `json:"CreatedAt,omitempty"`
	ID             *int64         `json:"ID,omitempty"`
	LastError      *string        `json:"LastError"`
	LastUsedAt     *time.Time     `json:"LastUsedAt"`
	MaxConcurrency *int           `json:"MaxConcurrency,omitempty"`
	Name           *string        `json:"Name,omitempty"`
	Status         *AccountStatus `json:"Status,omitempty"`
	Template       *Template      `json:"Template,omitempty"`
	TemplateID     *int64         `json:"TemplateID,omitempty"`
	UpdatedAt      *time.Time     `json:"UpdatedAt,omitempty"`
	UpstreamKey    *string        `json:"UpstreamKey,omitempty"`
	Weight         *int           `json:"Weight,omitempty"`
	Concurrency    *int64         `json:"concurrency,omitempty"`
	ErrCount       *int           `json:"err_count,omitempty"`
	ErrRate        *float64       `json:"err_rate,omitempty"`
}

// BatchDeleteBody defines model for BatchDeleteBody.
type BatchDeleteBody struct {
	Ids []int64 `json:"ids"`
}

// BatchDeleteResponse defines model for BatchDeleteResponse.
type BatchDeleteResponse struct {
	Deleted int `json:"deleted"`
}

// BatchUpdateAccountsBody defines model for BatchUpdateAccountsBody.
type BatchUpdateAccountsBody struct {
	Fields AccountPatch `json:"fields"`
	Ids    []int64      `json:"ids"`
}

// BatchUpdateGroupsBody defines model for BatchUpdateGroupsBody.
type BatchUpdateGroupsBody struct {
	Fields GroupPatch `json:"fields"`
	Ids    []int64    `json:"ids"`
}

// BatchUpdateResponse defines model for BatchUpdateResponse.
type BatchUpdateResponse struct {
	Updated int `json:"updated"`
}

// BatchUpdateTemplatesBody defines model for BatchUpdateTemplatesBody.
type BatchUpdateTemplatesBody struct {
	Fields TemplatePatch `json:"fields"`
	Ids    []int64       `json:"ids"`
}

// CreateGroupResponse defines model for CreateGroupResponse.
type CreateGroupResponse struct {
	Group Group  `json:"group"`
	Key   string `json:"key"`
}

// DeletedResponse defines model for DeletedResponse.
type DeletedResponse struct {
	Deleted bool `json:"deleted"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// ErrorType defines model for ErrorType.
type ErrorType string

// Group defines model for Group.
type Group struct {
	CreatedAt *time.Time `json:"CreatedAt,omitempty"`
	ID        *int64     `json:"ID,omitempty"`
	KeyHash   *string    `json:"KeyHash,omitempty"`
	KeyPrefix *string    `json:"KeyPrefix,omitempty"`
	Name      *string    `json:"Name,omitempty"`
	UpdatedAt *time.Time `json:"UpdatedAt,omitempty"`
}

// GroupCreate defines model for GroupCreate.
type GroupCreate struct {
	Name string `json:"name"`
}

// GroupListResponse defines model for GroupListResponse.
type GroupListResponse struct {
	Rows  []Group `json:"rows"`
	Total int64   `json:"total"`
}

// GroupPatch defines model for GroupPatch.
type GroupPatch struct {
	Name *string `json:"name,omitempty"`
}

// LogsResponse defines model for LogsResponse.
type LogsResponse struct {
	Rows  []UsageLog `json:"rows"`
	Total int64      `json:"total"`
}

// RequestFormat defines model for RequestFormat.
type RequestFormat string

// RotateKeyResponse defines model for RotateKeyResponse.
type RotateKeyResponse struct {
	Key string `json:"key"`
}

// Rule defines model for Rule.
type Rule struct {
	CreatedAt time.Time              `json:"CreatedAt"`
	Enabled   bool                   `json:"Enabled"`
	ID        int64                  `json:"ID"`
	Name      string                 `json:"Name"`
	Priority  int                    `json:"Priority"`
	Then      map[string]interface{} `json:"Then"`
	UpdatedAt time.Time              `json:"UpdatedAt"`
	When      map[string]interface{} `json:"When"`
}

// RuleCreate defines model for RuleCreate.
type RuleCreate struct {
	Enabled  *bool                   `json:"enabled,omitempty"`
	Name     string                  `json:"name"`
	Priority int                     `json:"priority"`
	Then     *map[string]interface{} `json:"then,omitempty"`
	When     *map[string]interface{} `json:"when,omitempty"`
}

// RuleListResponse defines model for RuleListResponse.
type RuleListResponse struct {
	Rows  []Rule `json:"rows"`
	Total int64  `json:"total"`
}

// RulePatch defines model for RulePatch.
type RulePatch struct {
	Enabled  *bool                   `json:"enabled,omitempty"`
	Name     *string                 `json:"name,omitempty"`
	Priority *int                    `json:"priority,omitempty"`
	Then     *map[string]interface{} `json:"then,omitempty"`
	When     *map[string]interface{} `json:"when,omitempty"`
}

// SetGroupAccountsBody defines model for SetGroupAccountsBody.
type SetGroupAccountsBody struct {
	AccountIds []int64 `json:"account_ids"`
}

// StatBucket defines model for StatBucket.
type StatBucket struct {
	AccountID        *int64     `json:"AccountID,omitempty"`
	BucketTime       *time.Time `json:"BucketTime,omitempty"`
	CompletionTokens *int64     `json:"CompletionTokens,omitempty"`
	ErrorCount       *int64     `json:"ErrorCount,omitempty"`
	GroupID          *int64     `json:"GroupID,omitempty"`
	IsError          *bool      `json:"IsError,omitempty"`
	Model            *string    `json:"Model,omitempty"`
	PromptTokens     *int64     `json:"PromptTokens,omitempty"`
	RequestCount     *int64     `json:"RequestCount,omitempty"`
	TemplateID       *int64     `json:"TemplateID,omitempty"`
	TotalLatencyMS   *int64     `json:"TotalLatencyMS,omitempty"`
	TotalTokens      *int64     `json:"TotalTokens,omitempty"`
}

// Template defines model for Template.
type Template struct {
	BaseURL          string                     `json:"BaseURL"`
	CreatedAt        time.Time                  `json:"CreatedAt"`
	FormatModels     *map[string][]string       `json:"FormatModels,omitempty"`
	ID               int64                      `json:"ID"`
	ModelMapping     *map[string]string         `json:"ModelMapping,omitempty"`
	Models           *[]string                  `json:"Models,omitempty"`
	Name             string                     `json:"Name"`
	SupportedFormats []TemplateSupportedFormats `json:"SupportedFormats"`
	UpdatedAt        time.Time                  `json:"UpdatedAt"`
}

// TemplateSupportedFormats defines model for Template.SupportedFormats.
type TemplateSupportedFormats string

// TemplateCreate defines model for TemplateCreate.
type TemplateCreate struct {
	BaseUrl          string                           `json:"base_url"`
	FormatModels     *map[string][]string             `json:"format_models,omitempty"`
	ModelMapping     *map[string]string               `json:"model_mapping,omitempty"`
	Models           *[]string                        `json:"models,omitempty"`
	Name             string                           `json:"name"`
	SupportedFormats []TemplateCreateSupportedFormats `json:"supported_formats"`
}

// TemplateCreateSupportedFormats defines model for TemplateCreate.SupportedFormats.
type TemplateCreateSupportedFormats string

// TemplateListResponse defines model for TemplateListResponse.
type TemplateListResponse struct {
	Rows  []Template `json:"rows"`
	Total int64      `json:"total"`
}

// TemplatePatch defines model for TemplatePatch.
type TemplatePatch struct {
	BaseUrl          *string                          `json:"base_url,omitempty"`
	FormatModels     *map[string][]string             `json:"format_models,omitempty"`
	ModelMapping     *map[string]string               `json:"model_mapping,omitempty"`
	Models           *[]string                        `json:"models,omitempty"`
	Name             *string                          `json:"name,omitempty"`
	SupportedFormats *[]TemplatePatchSupportedFormats `json:"supported_formats,omitempty"`
}

// TemplatePatchSupportedFormats defines model for TemplatePatch.SupportedFormats.
type TemplatePatchSupportedFormats string

// UpdatedResponse defines model for UpdatedResponse.
type UpdatedResponse struct {
	Updated bool `json:"updated"`
}

// UsageLog defines model for UsageLog.
type UsageLog struct {
	AccountID        *int64         `json:"AccountID,omitempty"`
	CompletionTokens *int64         `json:"CompletionTokens,omitempty"`
	CreatedAt        *time.Time     `json:"CreatedAt,omitempty"`
	ErrorType        *ErrorType     `json:"ErrorType,omitempty"`
	Format           *RequestFormat `json:"Format,omitempty"`
	GroupID          *int64         `json:"GroupID,omitempty"`
	ID               *int64         `json:"ID,omitempty"`
	LatencyMS        *int64         `json:"LatencyMS,omitempty"`
	MappedModel      *string        `json:"MappedModel"`
	Model            *string        `json:"Model,omitempty"`
	PromptTokens     *int64         `json:"PromptTokens,omitempty"`
	RequestID        *string        `json:"RequestID,omitempty"`
	StatusCode       *int           `json:"StatusCode,omitempty"`
	TemplateID       *int64         `json:"TemplateID,omitempty"`
	TotalTokens      *int64         `json:"TotalTokens,omitempty"`
}

// Error defines model for Error.
type Error = ErrorResponse

// GetAccountsParams defines parameters for GetAccounts.
type GetAccountsParams struct {
	Limit      *int                    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *int                    `form:"offset,omitempty" json:"offset,omitempty"`
	Name       *string                 `form:"name,omitempty" json:"name,omitempty"`
	Sort       *string                 `form:"sort,omitempty" json:"sort,omitempty"`
	Order      *GetAccountsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
	Status     *string                 `form:"status,omitempty" json:"status,omitempty"`
	TemplateId *int64                  `form:"template_id,omitempty" json:"template_id,omitempty"`
}

// GetAccountsParamsOrder defines parameters for GetAccounts.
type GetAccountsParamsOrder string

// GetGroupsParams defines parameters for GetGroups.
type GetGroupsParams struct {
	Limit  *int                  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                  `form:"offset,omitempty" json:"offset,omitempty"`
	Name   *string               `form:"name,omitempty" json:"name,omitempty"`
	Sort   *string               `form:"sort,omitempty" json:"sort,omitempty"`
	Order  *GetGroupsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// GetGroupsParamsOrder defines parameters for GetGroups.
type GetGroupsParamsOrder string

// GetLogsParams defines parameters for GetLogs.
type GetLogsParams struct {
	Limit      *int       `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *int       `form:"offset,omitempty" json:"offset,omitempty"`
	GroupId    *int64     `form:"group_id,omitempty" json:"group_id,omitempty"`
	AccountId  *int64     `form:"account_id,omitempty" json:"account_id,omitempty"`
	Model      *string    `form:"model,omitempty" json:"model,omitempty"`
	StatusCode *int       `form:"status_code,omitempty" json:"status_code,omitempty"`
	ErrorType  *string    `form:"error_type,omitempty" json:"error_type,omitempty"`
	From       *time.Time `form:"from,omitempty" json:"from,omitempty"`
	To         *time.Time `form:"to,omitempty" json:"to,omitempty"`
}

// ListRulesParams defines parameters for ListRules.
type ListRulesParams struct {
	Enabled *bool `form:"enabled,omitempty" json:"enabled,omitempty"`
}

// GetStatsParams defines parameters for GetStats.
type GetStatsParams struct {
	From        *time.Time                 `form:"from,omitempty" json:"from,omitempty"`
	To          *time.Time                 `form:"to,omitempty" json:"to,omitempty"`
	Granularity *GetStatsParamsGranularity `form:"granularity,omitempty" json:"granularity,omitempty"`
	GroupId     *int64                     `form:"group_id,omitempty" json:"group_id,omitempty"`
	AccountId   *int64                     `form:"account_id,omitempty" json:"account_id,omitempty"`
	Model       *string                    `form:"model,omitempty" json:"model,omitempty"`
}

// GetStatsParamsGranularity defines parameters for GetStats.
type GetStatsParamsGranularity string

// GetTemplatesParams defines parameters for GetTemplates.
type GetTemplatesParams struct {
	Limit  *int                     `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                     `form:"offset,omitempty" json:"offset,omitempty"`
	Name   *string                  `form:"name,omitempty" json:"name,omitempty"`
	Sort   *string                  `form:"sort,omitempty" json:"sort,omitempty"`
	Order  *GetTemplatesParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// GetTemplatesParamsOrder defines parameters for GetTemplates.
type GetTemplatesParamsOrder string

// PostAccountsJSONRequestBody defines body for PostAccounts for application/json ContentType.
type PostAccountsJSONRequestBody = AccountCreate

// PostAccountsBatchDeleteJSONRequestBody defines body for PostAccountsBatchDelete for application/json ContentType.
type PostAccountsBatchDeleteJSONRequestBody = BatchDeleteBody

// PostAccountsBatchUpdateJSONRequestBody defines body for PostAccountsBatchUpdate for application/json ContentType.
type PostAccountsBatchUpdateJSONRequestBody = BatchUpdateAccountsBody

// PutAccountsIdJSONRequestBody defines body for PutAccountsId for application/json ContentType.
type PutAccountsIdJSONRequestBody = AccountCreate

// PostGroupsJSONRequestBody defines body for PostGroups for application/json ContentType.
type PostGroupsJSONRequestBody = GroupCreate

// PostGroupsBatchDeleteJSONRequestBody defines body for PostGroupsBatchDelete for application/json ContentType.
type PostGroupsBatchDeleteJSONRequestBody = BatchDeleteBody

// PostGroupsBatchUpdateJSONRequestBody defines body for PostGroupsBatchUpdate for application/json ContentType.
type PostGroupsBatchUpdateJSONRequestBody = BatchUpdateGroupsBody

// PutGroupsIdJSONRequestBody defines body for PutGroupsId for application/json ContentType.
type PutGroupsIdJSONRequestBody = GroupCreate

// PutGroupsIdAccountsJSONRequestBody defines body for PutGroupsIdAccounts for application/json ContentType.
type PutGroupsIdAccountsJSONRequestBody = SetGroupAccountsBody

// CreateRuleJSONRequestBody defines body for CreateRule for application/json ContentType.
type CreateRuleJSONRequestBody = RuleCreate

// UpdateRuleJSONRequestBody defines body for UpdateRule for application/json ContentType.
type UpdateRuleJSONRequestBody = RulePatch

// PostTemplatesJSONRequestBody defines body for PostTemplates for application/json ContentType.
type PostTemplatesJSONRequestBody = TemplateCreate

// PostTemplatesBatchDeleteJSONRequestBody defines body for PostTemplatesBatchDelete for application/json ContentType.
type PostTemplatesBatchDeleteJSONRequestBody = BatchDeleteBody

// PostTemplatesBatchUpdateJSONRequestBody defines body for PostTemplatesBatchUpdate for application/json ContentType.
type PostTemplatesBatchUpdateJSONRequestBody = BatchUpdateTemplatesBody

// PutTemplatesIdJSONRequestBody defines body for PutTemplatesId for application/json ContentType.
type PutTemplatesIdJSONRequestBody = TemplateCreate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 账号列表（分页/筛选/排序，含运行时视图）
	// (GET /accounts)
	GetAccounts(w http.ResponseWriter, r *http.Request, params GetAccountsParams)
	// 创建账号
	// (POST /accounts)
	PostAccounts(w http.ResponseWriter, r *http.Request)
	// 批量删除账号（事务，全成或全败）
	// (POST /accounts/batch-delete)
	PostAccountsBatchDelete(w http.ResponseWriter, r *http.Request)
	// 批量更新账号（fields 为任意字段子集）
	// (POST /accounts/batch-update)
	PostAccountsBatchUpdate(w http.ResponseWriter, r *http.Request)

	// (DELETE /accounts/{id})
	DeleteAccountsId(w http.ResponseWriter, r *http.Request, id int64)

	// (GET /accounts/{id})
	GetAccountsId(w http.ResponseWriter, r *http.Request, id int64)

	// (PUT /accounts/{id})
	PutAccountsId(w http.ResponseWriter, r *http.Request, id int64)
	// 分组列表（分页/筛选/排序）
	// (GET /groups)
	GetGroups(w http.ResponseWriter, r *http.Request, params GetGroupsParams)
	// 创建分组（响应含明文 key，仅此一次）
	// (POST /groups)
	PostGroups(w http.ResponseWriter, r *http.Request)
	// 批量删除分组（事务，全成或全败）
	// (POST /groups/batch-delete)
	PostGroupsBatchDelete(w http.ResponseWriter, r *http.Request)
	// 批量更新分组（fields 为任意字段子集）
	// (POST /groups/batch-update)
	PostGroupsBatchUpdate(w http.ResponseWriter, r *http.Request)

	// (DELETE /groups/{id})
	DeleteGroupsId(w http.ResponseWriter, r *http.Request, id int64)

	// (GET /groups/{id})
	GetGroupsId(w http.ResponseWriter, r *http.Request, id int64)

	// (PUT /groups/{id})
	PutGroupsId(w http.ResponseWriter, r *http.Request, id int64)
	// 全量绑定账号集合
	// (PUT /groups/{id}/accounts)
	PutGroupsIdAccounts(w http.ResponseWriter, r *http.Request, id int64)
	// 轮换分组 key
	// (POST /groups/{id}/rotate-key)
	PostGroupsIdRotateKey(w http.ResponseWriter, r *http.Request, id int64)
	// 用量日志分页查询
	// (GET /logs)
	GetLogs(w http.ResponseWriter, r *http.Request, params GetLogsParams)
	// 规则列表（enabled 过滤，priority 升序）
	// (GET /rules)
	ListRules(w http.ResponseWriter, r *http.Request, params ListRulesParams)
	// 创建规则
	// (POST /rules)
	CreateRule(w http.ResponseWriter, r *http.Request)
	// 删除规则
	// (DELETE /rules/{id})
	DeleteRule(w http.ResponseWriter, r *http.Request, id int64)
	// 更新规则（fields 任意子集，未提供字段保持原值）
	// (PUT /rules/{id})
	UpdateRule(w http.ResponseWriter, r *http.Request, id int64)
	// 用量统计聚合
	// (GET /stats)
	GetStats(w http.ResponseWriter, r *http.Request, params GetStatsParams)
	// 模板列表（分页/筛选/排序）
	// (GET /templates)
	GetTemplates(w http.ResponseWriter, r *http.Request, params GetTemplatesParams)
	// 创建模板
	// (POST /templates)
	PostTemplates(w http.ResponseWriter, r *http.Request)
	// 批量删除模板（事务，全成或全败）
	// (POST /templates/batch-delete)
	PostTemplatesBatchDelete(w http.ResponseWriter, r *http.Request)
	// 批量更新模板（fields 为任意字段子集）
	// (POST /templates/batch-update)
	PostTemplatesBatchUpdate(w http.ResponseWriter, r *http.Request)

	// (DELETE /templates/{id})
	DeleteTemplatesId(w http.ResponseWriter, r *http.Request, id int64)

	// (GET /templates/{id})
	GetTemplatesId(w http.ResponseWriter, r *http.Request, id int64)

	// (PUT /templates/{id})
	PutTemplatesId(w http.ResponseWriter, r *http.Request, id int64)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// 账号列表（分页/筛选/排序，含运行时视图）
// (GET /accounts)
func (_ Unimplemented) GetAccounts(w http.ResponseWriter, r *http.Request, params GetAccountsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 创建账号
// (POST /accounts)
func (_ Unimplemented) PostAccounts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 批量删除账号（事务，全成或全败）
// (POST /accounts/batch-delete)
func (_ Unimplemented) PostAccountsBatchDelete(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 批量更新账号（fields 为任意字段子集）
// (POST /accounts/batch-update)
func (_ Unimplemented) PostAccountsBatchUpdate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /accounts/{id})
func (_ Unimplemented) DeleteAccountsId(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /accounts/{id})
func (_ Unimplemented) GetAccountsId(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /accounts/{id})
func (_ Unimplemented) PutAccountsId(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 分组列表（分页/筛选/排序）
// (GET /groups)
func (_ Unimplemented) GetGroups(w http.ResponseWriter, r *http.Request, params GetGroupsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 创建分组（响应含明文 key，仅此一次）
// (POST /groups)
func (_ Unimplemented) PostGroups(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 批量删除分组（事务，全成或全败）
// (POST /groups/batch-delete)
func (_ Unimplemented) PostGroupsBatchDelete(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 批量更新分组（fields 为任意字段子集）
// (POST /groups/batch-update)
func (_ Unimplemented) PostGroupsBatchUpdate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /groups/{id})
func (_ Unimplemented) DeleteGroupsId(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /groups/{id})
func (_ Unimplemented) GetGroupsId(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /groups/{id})
func (_ Unimplemented) PutGroupsId(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 全量绑定账号集合
// (PUT /groups/{id}/accounts)
func (_ Unimplemented) PutGroupsIdAccounts(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 轮换分组 key
// (POST /groups/{id}/rotate-key)
func (_ Unimplemented) PostGroupsIdRotateKey(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 用量日志分页查询
// (GET /logs)
func (_ Unimplemented) GetLogs(w http.ResponseWriter, r *http.Request, params GetLogsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 规则列表（enabled 过滤，priority 升序）
// (GET /rules)
func (_ Unimplemented) ListRules(w http.ResponseWriter, r *http.Request, params ListRulesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 创建规则
// (POST /rules)
func (_ Unimplemented) CreateRule(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 删除规则
// (DELETE /rules/{id})
func (_ Unimplemented) DeleteRule(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 更新规则（fields 任意子集，未提供字段保持原值）
// (PUT /rules/{id})
func (_ Unimplemented) UpdateRule(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 用量统计聚合
// (GET /stats)
func (_ Unimplemented) GetStats(w http.ResponseWriter, r *http.Request, params GetStatsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 模板列表（分页/筛选/排序）
// (GET /templates)
func (_ Unimplemented) GetTemplates(w http.ResponseWriter, r *http.Request, params GetTemplatesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 创建模板
// (POST /templates)
func (_ Unimplemented) PostTemplates(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 批量删除模板（事务，全成或全败）
// (POST /templates/batch-delete)
func (_ Unimplemented) PostTemplatesBatchDelete(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 批量更新模板（fields 为任意字段子集）
// (POST /templates/batch-update)
func (_ Unimplemented) PostTemplatesBatchUpdate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /templates/{id})
func (_ Unimplemented) DeleteTemplatesId(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /templates/{id})
func (_ Unimplemented) GetTemplatesId(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /templates/{id})
func (_ Unimplemented) PutTemplatesId(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAccounts operation middleware
func (siw *ServerInterfaceWrapper) GetAccounts(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAccountsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", r.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", r.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "template_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "template_id", r.URL.Query(), &params.TemplateId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "template_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccounts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAccounts operation middleware
func (siw *ServerInterfaceWrapper) PostAccounts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAccounts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAccountsBatchDelete operation middleware
func (siw *ServerInterfaceWrapper) PostAccountsBatchDelete(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAccountsBatchDelete(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAccountsBatchUpdate operation middleware
func (siw *ServerInterfaceWrapper) PostAccountsBatchUpdate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAccountsBatchUpdate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAccountsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteAccountsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAccountsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccountsId operation middleware
func (siw *ServerInterfaceWrapper) GetAccountsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccountsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutAccountsId operation middleware
func (siw *ServerInterfaceWrapper) PutAccountsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutAccountsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGroups operation middleware
func (siw *ServerInterfaceWrapper) GetGroups(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGroupsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", r.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", r.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGroups(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostGroups operation middleware
func (siw *ServerInterfaceWrapper) PostGroups(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostGroups(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostGroupsBatchDelete operation middleware
func (siw *ServerInterfaceWrapper) PostGroupsBatchDelete(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostGroupsBatchDelete(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostGroupsBatchUpdate operation middleware
func (siw *ServerInterfaceWrapper) PostGroupsBatchUpdate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostGroupsBatchUpdate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGroupsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteGroupsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGroupsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGroupsId operation middleware
func (siw *ServerInterfaceWrapper) GetGroupsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGroupsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutGroupsId operation middleware
func (siw *ServerInterfaceWrapper) PutGroupsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutGroupsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutGroupsIdAccounts operation middleware
func (siw *ServerInterfaceWrapper) PutGroupsIdAccounts(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutGroupsIdAccounts(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostGroupsIdRotateKey operation middleware
func (siw *ServerInterfaceWrapper) PostGroupsIdRotateKey(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostGroupsIdRotateKey(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLogs operation middleware
func (siw *ServerInterfaceWrapper) GetLogs(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLogsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "group_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "group_id", r.URL.Query(), &params.GroupId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "group_id", Err: err})
		return
	}

	// ------------- Optional query parameter "account_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "account_id", r.URL.Query(), &params.AccountId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "account_id", Err: err})
		return
	}

	// ------------- Optional query parameter "model" -------------

	err = runtime.BindQueryParameter("form", true, false, "model", r.URL.Query(), &params.Model)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "model", Err: err})
		return
	}

	// ------------- Optional query parameter "status_code" -------------

	err = runtime.BindQueryParameter("form", true, false, "status_code", r.URL.Query(), &params.StatusCode)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status_code", Err: err})
		return
	}

	// ------------- Optional query parameter "error_type" -------------

	err = runtime.BindQueryParameter("form", true, false, "error_type", r.URL.Query(), &params.ErrorType)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error_type", Err: err})
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", r.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, false, "to", r.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLogs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRules operation middleware
func (siw *ServerInterfaceWrapper) ListRules(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRulesParams

	// ------------- Optional query parameter "enabled" -------------

	err = runtime.BindQueryParameter("form", true, false, "enabled", r.URL.Query(), &params.Enabled)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "enabled", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRules(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRule operation middleware
func (siw *ServerInterfaceWrapper) CreateRule(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRule(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRule operation middleware
func (siw *ServerInterfaceWrapper) DeleteRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRule operation middleware
func (siw *ServerInterfaceWrapper) UpdateRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStats operation middleware
func (siw *ServerInterfaceWrapper) GetStats(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStatsParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", r.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, false, "to", r.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	// ------------- Optional query parameter "granularity" -------------

	err = runtime.BindQueryParameter("form", true, false, "granularity", r.URL.Query(), &params.Granularity)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "granularity", Err: err})
		return
	}

	// ------------- Optional query parameter "group_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "group_id", r.URL.Query(), &params.GroupId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "group_id", Err: err})
		return
	}

	// ------------- Optional query parameter "account_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "account_id", r.URL.Query(), &params.AccountId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "account_id", Err: err})
		return
	}

	// ------------- Optional query parameter "model" -------------

	err = runtime.BindQueryParameter("form", true, false, "model", r.URL.Query(), &params.Model)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "model", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStats(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTemplates operation middleware
func (siw *ServerInterfaceWrapper) GetTemplates(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTemplatesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", r.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", r.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTemplates(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTemplates operation middleware
func (siw *ServerInterfaceWrapper) PostTemplates(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTemplates(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTemplatesBatchDelete operation middleware
func (siw *ServerInterfaceWrapper) PostTemplatesBatchDelete(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTemplatesBatchDelete(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTemplatesBatchUpdate operation middleware
func (siw *ServerInterfaceWrapper) PostTemplatesBatchUpdate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTemplatesBatchUpdate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTemplatesId operation middleware
func (siw *ServerInterfaceWrapper) DeleteTemplatesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTemplatesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTemplatesId operation middleware
func (siw *ServerInterfaceWrapper) GetTemplatesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTemplatesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutTemplatesId operation middleware
func (siw *ServerInterfaceWrapper) PutTemplatesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutTemplatesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/accounts", wrapper.GetAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/accounts", wrapper.PostAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/accounts/batch-delete", wrapper.PostAccountsBatchDelete)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/accounts/batch-update", wrapper.PostAccountsBatchUpdate)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/accounts/{id}", wrapper.DeleteAccountsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/accounts/{id}", wrapper.GetAccountsId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/accounts/{id}", wrapper.PutAccountsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/groups", wrapper.GetGroups)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/groups", wrapper.PostGroups)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/groups/batch-delete", wrapper.PostGroupsBatchDelete)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/groups/batch-update", wrapper.PostGroupsBatchUpdate)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/groups/{id}", wrapper.DeleteGroupsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/groups/{id}", wrapper.GetGroupsId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/groups/{id}", wrapper.PutGroupsId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/groups/{id}/accounts", wrapper.PutGroupsIdAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/groups/{id}/rotate-key", wrapper.PostGroupsIdRotateKey)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/logs", wrapper.GetLogs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rules", wrapper.ListRules)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/rules", wrapper.CreateRule)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/rules/{id}", wrapper.DeleteRule)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/rules/{id}", wrapper.UpdateRule)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stats", wrapper.GetStats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/templates", wrapper.GetTemplates)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/templates", wrapper.PostTemplates)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/templates/batch-delete", wrapper.PostTemplatesBatchDelete)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/templates/batch-update", wrapper.PostTemplatesBatchUpdate)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/templates/{id}", wrapper.DeleteTemplatesId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/templates/{id}", wrapper.GetTemplatesId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/templates/{id}", wrapper.PutTemplatesId)
	})

	return r
}
