// Code generated by ent, DO NOT EDIT.

package imageprice

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/is7qin/c3api/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldLTE(FieldID, id))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldEQ(FieldModel, v))
}

// InputImageTokenPricePerMillion applies equality check predicate on the "input_image_token_price_per_million" field. It's identical to InputImageTokenPricePerMillionEQ.
func InputImageTokenPricePerMillion(v int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldEQ(FieldInputImageTokenPricePerMillion, v))
}

// OutputImageTokenPricePerMillion applies equality check predicate on the "output_image_token_price_per_million" field. It's identical to OutputImageTokenPricePerMillionEQ.
func OutputImageTokenPricePerMillion(v int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldEQ(FieldOutputImageTokenPricePerMillion, v))
}

// OutputCostPerImageMilli applies equality check predicate on the "output_cost_per_image_milli" field. It's identical to OutputCostPerImageMilliEQ.
func OutputCostPerImageMilli(v int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldEQ(FieldOutputCostPerImageMilli, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldEQ(FieldUpdatedAt, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldContainsFold(FieldModel, v))
}

// InputImageTokenPricePerMillionEQ applies the EQ predicate on the "input_image_token_price_per_million" field.
func InputImageTokenPricePerMillionEQ(v int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldEQ(FieldInputImageTokenPricePerMillion, v))
}

// InputImageTokenPricePerMillionNEQ applies the NEQ predicate on the "input_image_token_price_per_million" field.
func InputImageTokenPricePerMillionNEQ(v int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldNEQ(FieldInputImageTokenPricePerMillion, v))
}

// InputImageTokenPricePerMillionIn applies the In predicate on the "input_image_token_price_per_million" field.
func InputImageTokenPricePerMillionIn(vs ...int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldIn(FieldInputImageTokenPricePerMillion, vs...))
}

// InputImageTokenPricePerMillionNotIn applies the NotIn predicate on the "input_image_token_price_per_million" field.
func InputImageTokenPricePerMillionNotIn(vs ...int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldNotIn(FieldInputImageTokenPricePerMillion, vs...))
}

// InputImageTokenPricePerMillionGT applies the GT predicate on the "input_image_token_price_per_million" field.
func InputImageTokenPricePerMillionGT(v int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldGT(FieldInputImageTokenPricePerMillion, v))
}

// InputImageTokenPricePerMillionGTE applies the GTE predicate on the "input_image_token_price_per_million" field.
func InputImageTokenPricePerMillionGTE(v int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldGTE(FieldInputImageTokenPricePerMillion, v))
}

// InputImageTokenPricePerMillionLT applies the LT predicate on the "input_image_token_price_per_million" field.
func InputImageTokenPricePerMillionLT(v int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldLT(FieldInputImageTokenPricePerMillion, v))
}

// InputImageTokenPricePerMillionLTE applies the LTE predicate on the "input_image_token_price_per_million" field.
func InputImageTokenPricePerMillionLTE(v int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldLTE(FieldInputImageTokenPricePerMillion, v))
}

// InputImageTokenPricePerMillionIsNil applies the IsNil predicate on the "input_image_token_price_per_million" field.
func InputImageTokenPricePerMillionIsNil() predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldIsNull(FieldInputImageTokenPricePerMillion))
}

// InputImageTokenPricePerMillionNotNil applies the NotNil predicate on the "input_image_token_price_per_million" field.
func InputImageTokenPricePerMillionNotNil() predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldNotNull(FieldInputImageTokenPricePerMillion))
}

// OutputImageTokenPricePerMillionEQ applies the EQ predicate on the "output_image_token_price_per_million" field.
func OutputImageTokenPricePerMillionEQ(v int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldEQ(FieldOutputImageTokenPricePerMillion, v))
}

// OutputImageTokenPricePerMillionNEQ applies the NEQ predicate on the "output_image_token_price_per_million" field.
func OutputImageTokenPricePerMillionNEQ(v int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldNEQ(FieldOutputImageTokenPricePerMillion, v))
}

// OutputImageTokenPricePerMillionIn applies the In predicate on the "output_image_token_price_per_million" field.
func OutputImageTokenPricePerMillionIn(vs ...int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldIn(FieldOutputImageTokenPricePerMillion, vs...))
}

// OutputImageTokenPricePerMillionNotIn applies the NotIn predicate on the "output_image_token_price_per_million" field.
func OutputImageTokenPricePerMillionNotIn(vs ...int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldNotIn(FieldOutputImageTokenPricePerMillion, vs...))
}

// OutputImageTokenPricePerMillionGT applies the GT predicate on the "output_image_token_price_per_million" field.
func OutputImageTokenPricePerMillionGT(v int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldGT(FieldOutputImageTokenPricePerMillion, v))
}

// OutputImageTokenPricePerMillionGTE applies the GTE predicate on the "output_image_token_price_per_million" field.
func OutputImageTokenPricePerMillionGTE(v int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldGTE(FieldOutputImageTokenPricePerMillion, v))
}

// OutputImageTokenPricePerMillionLT applies the LT predicate on the "output_image_token_price_per_million" field.
func OutputImageTokenPricePerMillionLT(v int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldLT(FieldOutputImageTokenPricePerMillion, v))
}

// OutputImageTokenPricePerMillionLTE applies the LTE predicate on the "output_image_token_price_per_million" field.
func OutputImageTokenPricePerMillionLTE(v int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldLTE(FieldOutputImageTokenPricePerMillion, v))
}

// OutputImageTokenPricePerMillionIsNil applies the IsNil predicate on the "output_image_token_price_per_million" field.
func OutputImageTokenPricePerMillionIsNil() predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldIsNull(FieldOutputImageTokenPricePerMillion))
}

// OutputImageTokenPricePerMillionNotNil applies the NotNil predicate on the "output_image_token_price_per_million" field.
func OutputImageTokenPricePerMillionNotNil() predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldNotNull(FieldOutputImageTokenPricePerMillion))
}

// OutputCostPerImageMilliEQ applies the EQ predicate on the "output_cost_per_image_milli" field.
func OutputCostPerImageMilliEQ(v int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldEQ(FieldOutputCostPerImageMilli, v))
}

// OutputCostPerImageMilliNEQ applies the NEQ predicate on the "output_cost_per_image_milli" field.
func OutputCostPerImageMilliNEQ(v int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldNEQ(FieldOutputCostPerImageMilli, v))
}

// OutputCostPerImageMilliIn applies the In predicate on the "output_cost_per_image_milli" field.
func OutputCostPerImageMilliIn(vs ...int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldIn(FieldOutputCostPerImageMilli, vs...))
}

// OutputCostPerImageMilliNotIn applies the NotIn predicate on the "output_cost_per_image_milli" field.
func OutputCostPerImageMilliNotIn(vs ...int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldNotIn(FieldOutputCostPerImageMilli, vs...))
}

// OutputCostPerImageMilliGT applies the GT predicate on the "output_cost_per_image_milli" field.
func OutputCostPerImageMilliGT(v int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldGT(FieldOutputCostPerImageMilli, v))
}

// OutputCostPerImageMilliGTE applies the GTE predicate on the "output_cost_per_image_milli" field.
func OutputCostPerImageMilliGTE(v int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldGTE(FieldOutputCostPerImageMilli, v))
}

// OutputCostPerImageMilliLT applies the LT predicate on the "output_cost_per_image_milli" field.
func OutputCostPerImageMilliLT(v int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldLT(FieldOutputCostPerImageMilli, v))
}

// OutputCostPerImageMilliLTE applies the LTE predicate on the "output_cost_per_image_milli" field.
func OutputCostPerImageMilliLTE(v int64) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldLTE(FieldOutputCostPerImageMilli, v))
}

// OutputCostPerImageMilliIsNil applies the IsNil predicate on the "output_cost_per_image_milli" field.
func OutputCostPerImageMilliIsNil() predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldIsNull(FieldOutputCostPerImageMilli))
}

// OutputCostPerImageMilliNotNil applies the NotNil predicate on the "output_cost_per_image_milli" field.
func OutputCostPerImageMilliNotNil() predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldNotNull(FieldOutputCostPerImageMilli))
}

// RawIsNil applies the IsNil predicate on the "raw" field.
func RawIsNil() predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldIsNull(FieldRaw))
}

// RawNotNil applies the NotNil predicate on the "raw" field.
func RawNotNil() predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldNotNull(FieldRaw))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v Source) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v Source) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...Source) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...Source) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldNotIn(FieldSource, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ImagePrice {
	return predicate.ImagePrice(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ImagePrice) predicate.ImagePrice {
	return predicate.ImagePrice(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ImagePrice) predicate.ImagePrice {
	return predicate.ImagePrice(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ImagePrice) predicate.ImagePrice {
	return predicate.ImagePrice(sql.NotPredicates(p))
}
