// Code generated by ent, DO NOT EDIT.

package redemptionuse

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the redemptionuse type in the database.
	Label = "redemption_use"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCodeID holds the string denoting the code_id field in the database.
	FieldCodeID = "code_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldResourceExpiresAt holds the string denoting the resource_expires_at field in the database.
	FieldResourceExpiresAt = "resource_expires_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeCode holds the string denoting the code edge name in mutations.
	EdgeCode = "code"
	// Table holds the table name of the redemptionuse in the database.
	Table = "redemption_uses"
	// CodeTable is the table that holds the code relation/edge.
	CodeTable = "redemption_uses"
	// CodeInverseTable is the table name for the RedemptionCode entity.
	// It exists in this package in order to avoid circular dependency with the "redemptioncode" package.
	CodeInverseTable = "redemption_codes"
	// CodeColumn is the table column denoting the code relation/edge.
	CodeColumn = "code_id"
)

// Columns holds all SQL columns for redemptionuse fields.
var Columns = []string{
	FieldID,
	FieldCodeID,
	FieldUserID,
	FieldValue,
	FieldResourceExpiresAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the RedemptionUse queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCodeID orders the results by the code_id field.
func ByCodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodeID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByResourceExpiresAt orders the results by the resource_expires_at field.
func ByResourceExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceExpiresAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByCodeField orders the results by code field.
func ByCodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCodeStep(), sql.OrderByField(field, opts...))
	}
}
func newCodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CodeTable, CodeColumn),
	)
}
