// Code generated by ent, DO NOT EDIT.

package redemptionuse

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/is7qin/c3api/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldLTE(FieldID, id))
}

// CodeID applies equality check predicate on the "code_id" field. It's identical to CodeIDEQ.
func CodeID(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldEQ(FieldCodeID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldEQ(FieldUserID, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldEQ(FieldValue, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldEQ(FieldGroupID, v))
}

// ResourceExpiresAt applies equality check predicate on the "resource_expires_at" field. It's identical to ResourceExpiresAtEQ.
func ResourceExpiresAt(v time.Time) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldEQ(FieldResourceExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldEQ(FieldCreatedAt, v))
}

// CodeIDEQ applies the EQ predicate on the "code_id" field.
func CodeIDEQ(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldEQ(FieldCodeID, v))
}

// CodeIDNEQ applies the NEQ predicate on the "code_id" field.
func CodeIDNEQ(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldNEQ(FieldCodeID, v))
}

// CodeIDIn applies the In predicate on the "code_id" field.
func CodeIDIn(vs ...int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldIn(FieldCodeID, vs...))
}

// CodeIDNotIn applies the NotIn predicate on the "code_id" field.
func CodeIDNotIn(vs ...int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldNotIn(FieldCodeID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldLTE(FieldUserID, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldLTE(FieldValue, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldNotNull(FieldGroupID))
}

// ResourceExpiresAtEQ applies the EQ predicate on the "resource_expires_at" field.
func ResourceExpiresAtEQ(v time.Time) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldEQ(FieldResourceExpiresAt, v))
}

// ResourceExpiresAtNEQ applies the NEQ predicate on the "resource_expires_at" field.
func ResourceExpiresAtNEQ(v time.Time) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldNEQ(FieldResourceExpiresAt, v))
}

// ResourceExpiresAtIn applies the In predicate on the "resource_expires_at" field.
func ResourceExpiresAtIn(vs ...time.Time) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldIn(FieldResourceExpiresAt, vs...))
}

// ResourceExpiresAtNotIn applies the NotIn predicate on the "resource_expires_at" field.
func ResourceExpiresAtNotIn(vs ...time.Time) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldNotIn(FieldResourceExpiresAt, vs...))
}

// ResourceExpiresAtGT applies the GT predicate on the "resource_expires_at" field.
func ResourceExpiresAtGT(v time.Time) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldGT(FieldResourceExpiresAt, v))
}

// ResourceExpiresAtGTE applies the GTE predicate on the "resource_expires_at" field.
func ResourceExpiresAtGTE(v time.Time) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldGTE(FieldResourceExpiresAt, v))
}

// ResourceExpiresAtLT applies the LT predicate on the "resource_expires_at" field.
func ResourceExpiresAtLT(v time.Time) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldLT(FieldResourceExpiresAt, v))
}

// ResourceExpiresAtLTE applies the LTE predicate on the "resource_expires_at" field.
func ResourceExpiresAtLTE(v time.Time) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldLTE(FieldResourceExpiresAt, v))
}

// ResourceExpiresAtIsNil applies the IsNil predicate on the "resource_expires_at" field.
func ResourceExpiresAtIsNil() predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldIsNull(FieldResourceExpiresAt))
}

// ResourceExpiresAtNotNil applies the NotNil predicate on the "resource_expires_at" field.
func ResourceExpiresAtNotNil() predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldNotNull(FieldResourceExpiresAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.FieldLTE(FieldCreatedAt, v))
}

// HasCode applies the HasEdge predicate on the "code" edge.
func HasCode() predicate.RedemptionUse {
	return predicate.RedemptionUse(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CodeTable, CodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCodeWith applies the HasEdge predicate on the "code" edge with a given conditions (other predicates).
func HasCodeWith(preds ...predicate.RedemptionCode) predicate.RedemptionUse {
	return predicate.RedemptionUse(func(s *sql.Selector) {
		step := newCodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RedemptionUse) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RedemptionUse) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RedemptionUse) predicate.RedemptionUse {
	return predicate.RedemptionUse(sql.NotPredicates(p))
}
