// Code generated by ent, DO NOT EDIT.

package pricing

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the pricing type in the database.
	Label = "pricing"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldPromptPricePerMillion holds the string denoting the prompt_price_per_million field in the database.
	FieldPromptPricePerMillion = "prompt_price_per_million"
	// FieldCompletionPricePerMillion holds the string denoting the completion_price_per_million field in the database.
	FieldCompletionPricePerMillion = "completion_price_per_million"
	// FieldMaxInputTokens holds the string denoting the max_input_tokens field in the database.
	FieldMaxInputTokens = "max_input_tokens"
	// FieldMaxOutputTokens holds the string denoting the max_output_tokens field in the database.
	FieldMaxOutputTokens = "max_output_tokens"
	// FieldCacheReadPricePerMillion holds the string denoting the cache_read_price_per_million field in the database.
	FieldCacheReadPricePerMillion = "cache_read_price_per_million"
	// FieldCacheCreationPricePerMillion holds the string denoting the cache_creation_price_per_million field in the database.
	FieldCacheCreationPricePerMillion = "cache_creation_price_per_million"
	// FieldPriorityPromptPricePerMillion holds the string denoting the priority_prompt_price_per_million field in the database.
	FieldPriorityPromptPricePerMillion = "priority_prompt_price_per_million"
	// FieldPriorityCompletionPricePerMillion holds the string denoting the priority_completion_price_per_million field in the database.
	FieldPriorityCompletionPricePerMillion = "priority_completion_price_per_million"
	// FieldPriorityCacheReadPricePerMillion holds the string denoting the priority_cache_read_price_per_million field in the database.
	FieldPriorityCacheReadPricePerMillion = "priority_cache_read_price_per_million"
	// FieldPriorityCacheCreationPricePerMillion holds the string denoting the priority_cache_creation_price_per_million field in the database.
	FieldPriorityCacheCreationPricePerMillion = "priority_cache_creation_price_per_million"
	// FieldFlexPromptPricePerMillion holds the string denoting the flex_prompt_price_per_million field in the database.
	FieldFlexPromptPricePerMillion = "flex_prompt_price_per_million"
	// FieldFlexCompletionPricePerMillion holds the string denoting the flex_completion_price_per_million field in the database.
	FieldFlexCompletionPricePerMillion = "flex_completion_price_per_million"
	// FieldFlexCacheReadPricePerMillion holds the string denoting the flex_cache_read_price_per_million field in the database.
	FieldFlexCacheReadPricePerMillion = "flex_cache_read_price_per_million"
	// FieldFlexCacheCreationPricePerMillion holds the string denoting the flex_cache_creation_price_per_million field in the database.
	FieldFlexCacheCreationPricePerMillion = "flex_cache_creation_price_per_million"
	// FieldAboveThreshold holds the string denoting the above_threshold field in the database.
	FieldAboveThreshold = "above_threshold"
	// FieldAbovePromptPricePerMillion holds the string denoting the above_prompt_price_per_million field in the database.
	FieldAbovePromptPricePerMillion = "above_prompt_price_per_million"
	// FieldAboveCompletionPricePerMillion holds the string denoting the above_completion_price_per_million field in the database.
	FieldAboveCompletionPricePerMillion = "above_completion_price_per_million"
	// FieldAboveCacheReadPricePerMillion holds the string denoting the above_cache_read_price_per_million field in the database.
	FieldAboveCacheReadPricePerMillion = "above_cache_read_price_per_million"
	// FieldAboveCacheCreationPricePerMillion holds the string denoting the above_cache_creation_price_per_million field in the database.
	FieldAboveCacheCreationPricePerMillion = "above_cache_creation_price_per_million"
	// FieldAbovePriorityPromptPricePerMillion holds the string denoting the above_priority_prompt_price_per_million field in the database.
	FieldAbovePriorityPromptPricePerMillion = "above_priority_prompt_price_per_million"
	// FieldAbovePriorityCompletionPricePerMillion holds the string denoting the above_priority_completion_price_per_million field in the database.
	FieldAbovePriorityCompletionPricePerMillion = "above_priority_completion_price_per_million"
	// FieldAbovePriorityCacheReadPricePerMillion holds the string denoting the above_priority_cache_read_price_per_million field in the database.
	FieldAbovePriorityCacheReadPricePerMillion = "above_priority_cache_read_price_per_million"
	// FieldAbovePriorityCacheCreationPricePerMillion holds the string denoting the above_priority_cache_creation_price_per_million field in the database.
	FieldAbovePriorityCacheCreationPricePerMillion = "above_priority_cache_creation_price_per_million"
	// FieldAboveFlexPromptPricePerMillion holds the string denoting the above_flex_prompt_price_per_million field in the database.
	FieldAboveFlexPromptPricePerMillion = "above_flex_prompt_price_per_million"
	// FieldAboveFlexCompletionPricePerMillion holds the string denoting the above_flex_completion_price_per_million field in the database.
	FieldAboveFlexCompletionPricePerMillion = "above_flex_completion_price_per_million"
	// FieldAboveFlexCacheReadPricePerMillion holds the string denoting the above_flex_cache_read_price_per_million field in the database.
	FieldAboveFlexCacheReadPricePerMillion = "above_flex_cache_read_price_per_million"
	// FieldAboveFlexCacheCreationPricePerMillion holds the string denoting the above_flex_cache_creation_price_per_million field in the database.
	FieldAboveFlexCacheCreationPricePerMillion = "above_flex_cache_creation_price_per_million"
	// FieldFastMultiplier holds the string denoting the fast_multiplier field in the database.
	FieldFastMultiplier = "fast_multiplier"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldSupportsPromptCaching holds the string denoting the supports_prompt_caching field in the database.
	FieldSupportsPromptCaching = "supports_prompt_caching"
	// FieldRaw holds the string denoting the raw field in the database.
	FieldRaw = "raw"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the pricing in the database.
	Table = "pricings"
)

// Columns holds all SQL columns for pricing fields.
var Columns = []string{
	FieldID,
	FieldModel,
	FieldPromptPricePerMillion,
	FieldCompletionPricePerMillion,
	FieldMaxInputTokens,
	FieldMaxOutputTokens,
	FieldCacheReadPricePerMillion,
	FieldCacheCreationPricePerMillion,
	FieldPriorityPromptPricePerMillion,
	FieldPriorityCompletionPricePerMillion,
	FieldPriorityCacheReadPricePerMillion,
	FieldPriorityCacheCreationPricePerMillion,
	FieldFlexPromptPricePerMillion,
	FieldFlexCompletionPricePerMillion,
	FieldFlexCacheReadPricePerMillion,
	FieldFlexCacheCreationPricePerMillion,
	FieldAboveThreshold,
	FieldAbovePromptPricePerMillion,
	FieldAboveCompletionPricePerMillion,
	FieldAboveCacheReadPricePerMillion,
	FieldAboveCacheCreationPricePerMillion,
	FieldAbovePriorityPromptPricePerMillion,
	FieldAbovePriorityCompletionPricePerMillion,
	FieldAbovePriorityCacheReadPricePerMillion,
	FieldAbovePriorityCacheCreationPricePerMillion,
	FieldAboveFlexPromptPricePerMillion,
	FieldAboveFlexCompletionPricePerMillion,
	FieldAboveFlexCacheReadPricePerMillion,
	FieldAboveFlexCacheCreationPricePerMillion,
	FieldFastMultiplier,
	FieldProvider,
	FieldMode,
	FieldSupportsPromptCaching,
	FieldRaw,
	FieldSource,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Source defines the type for the "source" enum field.
type Source string

// Source values.
const (
	SourceLitellm Source = "litellm"
	SourceManual  Source = "manual"
)

func (s Source) String() string {
	return string(s)
}

// SourceValidator is a validator for the "source" field enum values. It is called by the builders before save.
func SourceValidator(s Source) error {
	switch s {
	case SourceLitellm, SourceManual:
		return nil
	default:
		return fmt.Errorf("pricing: invalid enum value for source field: %q", s)
	}
}

// OrderOption defines the ordering options for the Pricing queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByPromptPricePerMillion orders the results by the prompt_price_per_million field.
func ByPromptPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptPricePerMillion, opts...).ToFunc()
}

// ByCompletionPricePerMillion orders the results by the completion_price_per_million field.
func ByCompletionPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletionPricePerMillion, opts...).ToFunc()
}

// ByMaxInputTokens orders the results by the max_input_tokens field.
func ByMaxInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxInputTokens, opts...).ToFunc()
}

// ByMaxOutputTokens orders the results by the max_output_tokens field.
func ByMaxOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxOutputTokens, opts...).ToFunc()
}

// ByCacheReadPricePerMillion orders the results by the cache_read_price_per_million field.
func ByCacheReadPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheReadPricePerMillion, opts...).ToFunc()
}

// ByCacheCreationPricePerMillion orders the results by the cache_creation_price_per_million field.
func ByCacheCreationPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheCreationPricePerMillion, opts...).ToFunc()
}

// ByPriorityPromptPricePerMillion orders the results by the priority_prompt_price_per_million field.
func ByPriorityPromptPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriorityPromptPricePerMillion, opts...).ToFunc()
}

// ByPriorityCompletionPricePerMillion orders the results by the priority_completion_price_per_million field.
func ByPriorityCompletionPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriorityCompletionPricePerMillion, opts...).ToFunc()
}

// ByPriorityCacheReadPricePerMillion orders the results by the priority_cache_read_price_per_million field.
func ByPriorityCacheReadPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriorityCacheReadPricePerMillion, opts...).ToFunc()
}

// ByPriorityCacheCreationPricePerMillion orders the results by the priority_cache_creation_price_per_million field.
func ByPriorityCacheCreationPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriorityCacheCreationPricePerMillion, opts...).ToFunc()
}

// ByFlexPromptPricePerMillion orders the results by the flex_prompt_price_per_million field.
func ByFlexPromptPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFlexPromptPricePerMillion, opts...).ToFunc()
}

// ByFlexCompletionPricePerMillion orders the results by the flex_completion_price_per_million field.
func ByFlexCompletionPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFlexCompletionPricePerMillion, opts...).ToFunc()
}

// ByFlexCacheReadPricePerMillion orders the results by the flex_cache_read_price_per_million field.
func ByFlexCacheReadPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFlexCacheReadPricePerMillion, opts...).ToFunc()
}

// ByFlexCacheCreationPricePerMillion orders the results by the flex_cache_creation_price_per_million field.
func ByFlexCacheCreationPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFlexCacheCreationPricePerMillion, opts...).ToFunc()
}

// ByAboveThreshold orders the results by the above_threshold field.
func ByAboveThreshold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAboveThreshold, opts...).ToFunc()
}

// ByAbovePromptPricePerMillion orders the results by the above_prompt_price_per_million field.
func ByAbovePromptPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAbovePromptPricePerMillion, opts...).ToFunc()
}

// ByAboveCompletionPricePerMillion orders the results by the above_completion_price_per_million field.
func ByAboveCompletionPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAboveCompletionPricePerMillion, opts...).ToFunc()
}

// ByAboveCacheReadPricePerMillion orders the results by the above_cache_read_price_per_million field.
func ByAboveCacheReadPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAboveCacheReadPricePerMillion, opts...).ToFunc()
}

// ByAboveCacheCreationPricePerMillion orders the results by the above_cache_creation_price_per_million field.
func ByAboveCacheCreationPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAboveCacheCreationPricePerMillion, opts...).ToFunc()
}

// ByAbovePriorityPromptPricePerMillion orders the results by the above_priority_prompt_price_per_million field.
func ByAbovePriorityPromptPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAbovePriorityPromptPricePerMillion, opts...).ToFunc()
}

// ByAbovePriorityCompletionPricePerMillion orders the results by the above_priority_completion_price_per_million field.
func ByAbovePriorityCompletionPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAbovePriorityCompletionPricePerMillion, opts...).ToFunc()
}

// ByAbovePriorityCacheReadPricePerMillion orders the results by the above_priority_cache_read_price_per_million field.
func ByAbovePriorityCacheReadPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAbovePriorityCacheReadPricePerMillion, opts...).ToFunc()
}

// ByAbovePriorityCacheCreationPricePerMillion orders the results by the above_priority_cache_creation_price_per_million field.
func ByAbovePriorityCacheCreationPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAbovePriorityCacheCreationPricePerMillion, opts...).ToFunc()
}

// ByAboveFlexPromptPricePerMillion orders the results by the above_flex_prompt_price_per_million field.
func ByAboveFlexPromptPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAboveFlexPromptPricePerMillion, opts...).ToFunc()
}

// ByAboveFlexCompletionPricePerMillion orders the results by the above_flex_completion_price_per_million field.
func ByAboveFlexCompletionPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAboveFlexCompletionPricePerMillion, opts...).ToFunc()
}

// ByAboveFlexCacheReadPricePerMillion orders the results by the above_flex_cache_read_price_per_million field.
func ByAboveFlexCacheReadPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAboveFlexCacheReadPricePerMillion, opts...).ToFunc()
}

// ByAboveFlexCacheCreationPricePerMillion orders the results by the above_flex_cache_creation_price_per_million field.
func ByAboveFlexCacheCreationPricePerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAboveFlexCacheCreationPricePerMillion, opts...).ToFunc()
}

// ByFastMultiplier orders the results by the fast_multiplier field.
func ByFastMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFastMultiplier, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByMode orders the results by the mode field.
func ByMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMode, opts...).ToFunc()
}

// BySupportsPromptCaching orders the results by the supports_prompt_caching field.
func BySupportsPromptCaching(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupportsPromptCaching, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
